# Topic modeling with BERTopic

BERTopic est un modèle de sujet qui exploite les techniques de clustering et une variante de TF-IDF basée sur les classes pour la génération des sujets :
1. création des document embeddings à l'aide d'un modèle de langage pré-entraîné 
2. réduction de la dimensionnalité des embeddings des documents avant de créer des clusters de documents sémantiquement similaires, chacun représentant un sujet distinct
3. application d'une version de TF-IDF basée sur les classes afin d'extraire la représentation des sujets (*topic representation*) de chaque sujet.

*Topic* est un cluster de documents sémantiquement similaires
*Topic representation* est la façon dont les sujets sont décrits ou labélisés, ici par un set de mots extraits des documents du cluster.

=> https://medialab.sciencespo.fr/actu/les-enjeux-de-linformation-a-lere-numerique-vus-par-les-francais/

In [2]:
import polars as pl
from nltk.corpus import stopwords
# from spacy.lang.fr.stop_words import STOP_WORDS
# from spacy.lang.en.stop_words import STOP_WORDS
from spacy.lang.zh.stop_words import STOP_WORDS
from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN
from bertopic.vectorizers import ClassTfidfTransformer
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
from bertopic import BERTopic

In [ ]:
# nous avons besoin de `protobuf` version 3.20 pour `SentenceTransformer` avec camembert
# !pip install protobuf==3.20.0

# Préparation des données

Les modèles de sujet avec transformers et word-embedding ne demande, en théorie, aucun prétraitement des données. Cependant, il peut s'avérer utile de normaliser les données, d'enlever les balises HTML (quand ce n'est pas déjà fait), etc. Dans le cas de certains corpus, la suppression de mots spécifiques présents dans tout le corpus peut également s'avérer utile. Après cela, on peut transformer notre dataframe en list de documents.

In [3]:
input_file = "../data/danmaku.csv"

docs = pl.read_csv(input_file).with_columns(
    pl.col("text").str.normalize("NFC")
).filter(
    pl.col("text").is_not_null()
).get_column(
    "text"
).to_list() # remplacer captions par la colonne contenant vos publications
docs[0]

'看成皮眼子（错乱）'

In [4]:
len(docs)

14333

Après cela, nous préparons une liste de mots vides, que nous exclurons de la représentation des sujets.

In [5]:
stoplist = list(STOP_WORDS)
# ADDITIONAL_STOPWORDS = []
# stoplist.extend(ADDITIONAL_STOPWORDS)
stoplist[:5]

['但是', '千', '那样', '一定', '运用']

# Vectoriser les données

### Word embeddings

La première étape consiste à transformer une chaîne (phrase) en un tableau de nombres (vecteur), autrement dit à vectoriser le texte.
BERTopic peut convertir les documents en embeddings. Cependant, ce processus peut être très coûteux. Il est donc possible de calculer ces embeddings une seule fois et de les transmettre à BERTopic pour éviter de les calculer à chaque fois.

=> https://www.sbert.net/docs/sentence_transformer/pretrained_models.html
=> https://huggingface.co/spaces/mteb/leaderboard

In [1]:
from transformers import AutoModel, AutoTokenizer

model_name = "sentence-transformers/distiluse-base-multilingual-cased-v1"
local_path = f"../model/{model_name}"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

# tokenizer.save_pretrained(local_path)
# model.save_pretrained(local_path)

tokenizer_config.json:   0%|          | 0.00/452 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/556 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/539M [00:00<?, ?B/s]

In [9]:
sentences = ["真不知道这种主播是怎么火的", "游戏玩得菜还只会pua观众"]

embedding_model = SentenceTransformer(model_name) # ("all-MiniLM-L6-v2")
example_embeddings = embedding_model.encode(sentences, show_progress_bar=True)

print(f"Sentence 1 has {len(sentences[0])} characters, and the embedding is {len(example_embeddings[0])} long.")
print(f"Sentence 2 has {len(sentences[1])} characters, and the embedding is {len(example_embeddings[1])} long.")

modules.json:   0%|          | 0.00/341 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/2.24k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/114 [00:00<?, ?B/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Sentence 1 has 13 characters, and the embedding is 512 long.
Sentence 2 has 13 characters, and the embedding is 512 long.

Comme le montre la cellule ci-dessus, les embeddings continues créées par le transformateur de phrases `dangvantuan/sentence-camembert-base` ont la même longueur, malgré des phrases de longueurs différentes. Ces embeddings continues ont la même longueur car, plutôt que de représenter directement les mots sous forme de nombres (c'est-à-dire de « sac de mots »), le transformateur crée une représentation riche prenant en compte 768 dimensions.

=> https://github.com/MaartenGr/BERTopic/discussions/822

### UMAP

BERTopic utilise généralement un algorithme de réduction de dimensionnalité (*dimensionality reduction algorithm*) pour réduire la taille des embeddings. Ceci permet d'éviter, dans une certaine mesure, le fléau de la dimension (https://en.wikipedia.org/wiki/Curse_of_dimensionality). 

UMAP est utilisé pour réduire l'espace dimensionnel. Cependant, il affiche par défaut un comportement stochastique qui produit des résultats différents à chaque exécution. Pour éviter cela pendant la période de test, nous pouvons définir un random_state du modèle avant de le transmettre à BERTopic.

```python
UMAP(angular_rp_forest=True, metric='cosine', n_components=10, n_neighbors=30, min_dist=0.1, random_state=42)
```

=> https://umap-learn.readthedocs.io/en/latest/parameters.html

### HDBSCAN

`nr_topics` est le paramètre qui permet de contrôler le nombre de sujets en fusionnant les sujets après leur création. Il permet de créer un nombre fixe de sujets. Il est toutefois conseillé de contrôler le nombre de sujets via le modèle de cluster, HDBSCAN par défaut. HDBSCAN possède un paramètre, `min_cluster_size`, qui contrôle indirectement le nombre de sujets créés. Un `min_cluster_size` élevé génère moins de sujets, tandis qu'un `min_cluster_size` faible en génère davantage.

```python
HDBSCAN(min_cluster_size=13, min_samples=3, prediction_data=True, metric='euclidean', cluster_selection_method='eom')
```

=> https://scikit-learn.org/stable/modules/generated/sklearn.cluster.HDBSCAN.html

### CountVectorizer

La représentation par défaut des sujets est calculée via c-TF-IDF. Cependant, c-TF-IDF s'appuie sur CountVectorizer, qui convertit le texte en unités. Grâce à CountVectorizer, nous pouvons effectuer plusieurs opérations : supprimer les mots vides, ignorer les mots rares, augmenter la range des n-gram. En d'autres termes, nous pouvons prétraiter les représentations des sujets après l'attribution des documents aux sujets. Cela n'aura aucune incidence sur le processus de clustering.

La tokenisation se fait automatiquement au niveau des espaces, pour le chinois il faut rajouter :

```python
import jieba

def tokenize_zh(text):
    words = jieba.lcut(text)
    return words

vectorizer = CountVectorizer(tokenizer=tokenize_zh)
```

### Construction du modèle

=> https://maartengr.github.io/BERTopic/getting_started/parameter%20tuning/parametertuning.html

In [10]:
import jieba

def tokenize_zh(text):
    words = jieba.lcut(text)
    return words

vectorizer = CountVectorizer(tokenizer=tokenize_zh)

In [11]:
def set_model_parameters(embedding_model=embedding_model, tokenizer=tokenize_zh):

    # Step 1 - extraction des embeddings
    # embedding_model = embedding_model

    # Step 2 - réduction des dimensionalité
    umap_model = UMAP(angular_rp_forest=True, metric='cosine', n_components=10, n_neighbors=30, min_dist=0.1)

    # Step 3 - Cluster reduced embeddings
    hdbscan_model = HDBSCAN(min_cluster_size=5, min_samples=5, prediction_data=True, metric='euclidean', cluster_selection_method='eom')
    # hdbscan_model = KMeans(n_clusters=50)
    # hdbscan_model = sklearn.cluster.AgglomerativeClustering(n_clusters=50)

    # Step 4 - Tokenisation des topics

    stoplist = list(STOP_WORDS)
    # ADDITIONAL_STOPWORDS = ["qu", "ya", "faut", "euh"]
    # stoplist.extend(ADDITIONAL_STOPWORDS)

    vectorizer_model = CountVectorizer(stop_words=stoplist, ngram_range=(1, 3), max_df=0.5, tokenizer=tokenizer)

    # Step 5 - Création de la représentation des topics
    ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True, bm25_weighting=True)

    # Topic model
    return BERTopic(
        embedding_model=embedding_model,
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        vectorizer_model=vectorizer_model,
        ctfidf_model=ctfidf_model,
        language='chinese',
        n_gram_range=(1,3),
        nr_topics="auto"
        
    )

# Entrainement du modèle

On encode tous les documents de notre corpus.

In [12]:
# embedding_model = SentenceTransformer("dangvantuan/sentence-camembert-base")
embeddings = embedding_model.encode(docs, show_progress_bar=True)

Batches:   0%|          | 0/448 [00:00<?, ?it/s]

On crée une instance du modèle avec tous les paramètres définis et notre modèle d'embeddings.

In [13]:
topic_model = set_model_parameters(embedding_model)

On ajuste le modèle aux documents de notre corpus et aux embeddings que nous avons préparés.

In [14]:
topic_model.fit(docs, embeddings)

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Building prefix dict from the default dictionary ...
Dumping model to file cache /var/folders/s9/j56343l57_s2lw7_47rw2bpr0000gn/T/jieba.cache
Loading model cost 0.363 seconds.
Prefix dict has been built successfully.

-1 est un "faux" cluster contenant toutes les valeurs aberrantes (*outliers*) ; il ne faut donc pas le prendre en compte. Un nom représentatif est attribué à chaque sujet. Le nom par défaut est un identifiant numérique suivi des mots-clés les plus représentatifs.

In [15]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,4293,-1_模拟_社会_时代_机飞,"[模拟, 社会, 时代, 机飞, 机飞 机飞, 时代 , 意识, 发展, 人工智能, 机飞...",[人工智能的终极形态是智人，完全是另外一种生物，和人工无关了。这还仅仅是人类可以理解的一种生...
1,0,448,0_ 声音_声音 _chatgpt_gpt 声音,"[ 声音, 声音 , chatgpt, gpt 声音, 配音, gpt4, 配音, ...","[你换个国内ai读搞不行吗，我听这香蕉口音真的听不清, 前面的红字 chatgpt是不用联..."
2,1,394,1_\ _\ _ 喔_喔,"[\ , \ , 喔, 喔 , 喔 , 喔, 喔, \, siu...","[喔！, 喔, @Cate Blanchett]"
3,2,255,2_逼 牛_ 牛 _牛 _ 牛 逼,"[逼 牛, 牛 , 牛 , 牛 逼, 牛 牛, 牛, 牛蛙, 牛...","[牛魔的我想听完这个故事其实，之前版本的编故事编的其实一般, 这个共享桌面牛了 相当于和全能..."
4,3,220,3_ 10 _10 _ 10_ 10,"[ 10 , 10 , 10, 10, 10 , 10 10, ...","[33？维斯塔潘！, 4o for all, 什么？10 个？]"
...,...,...,...,...,...
340,339,5,339_福音_福音 _快速 消除_患者 福音,"[福音, 福音 , 快速 消除, 患者 福音, 宅 男, 塌房 明星, 宅女 福音...","[宅男福音, 塌房明星快速消除术，真是福音呐, 帕金森患者的福音]"
341,340,5,340_源神_源神 启动_ 源神_启动,"[源神, 源神 启动, 源神, 启动, 启动 , 股神 启动 , 源神 启动, ...","[神识系统开启, 这下真是源神启动了, 源神 启动！]"
342,341,5,341_葛 大爷_葛_大爷_葛 大爷 哈哈哈,"[葛 大爷, 葛, 大爷, 葛 大爷 哈哈哈, 喷 点, 瘸 哈哈哈, 哈哈哈 大佬...","[哈哈，大佬也热衷于对喷, Ai爆发了文员完蛋了, 点进来还以为是葛大爷哈哈哈哈哈]"
343,342,5,342_算命 _算命_真的 能用 ai_真的 能用,"[算命 , 算命, 真的 能用 ai, 真的 能用, 终于 算命, 云 计算, 能...","[终于能算命了, 真的能用ai算命了, 意思是不是云计算？本地计算？]"
344,343,5,343_路线 这才_路线 _ 路线 _ 路线,"[路线 这才, 路线 , 路线 , 路线, 这才 , 这才 , 路线...","[这也不对啊, 这不一个路线么, 这才对嘛]"

In [16]:
topic_model.get_topic(1)

[('\\    ', 0.24710525839535896),
 ('\\  ', 0.24710525839535896),
 ('    喔', 0.24710525839535896),
 ('喔  ', 0.24710525839535896),
 ('  喔  ', 0.24710525839535896),
 ('喔', 0.23107368016344865),
 ('  喔', 0.23107368016344865),
 ('\\', 0.21909953644730956),
 ('siuuuuuu    ', 0.1919399564231392),
 ('what    ', 0.1919399564231392)]

In [17]:
topic_model.generate_topic_labels(nr_words=20, topic_prefix=True, word_length=None, separator='  --  ')

['-1  --  模拟  --  社会  --  时代  --  机飞  --  机飞 机飞  --  时代    --  意识  --  发展  --  人工智能  --  机飞 机飞 机飞',
 '0  --    声音  --  声音    --  chatgpt  --  gpt 声音  --    配音  --  gpt4  --  配音  --    gpt 声音  --  gpt 声音    --  配音  ',
 '1  --  \\      --  \\    --      喔  --  喔    --    喔    --  喔  --    喔  --  \\  --  siuuuuuu      --  what    ',
 '2  --  逼   牛  --    牛    --  牛    --    牛 逼  --  牛   牛  --    牛  --    牛蛙  --  牛蛙    --    牛蛙    --  牛蛙',
 '3  --    10    --  10    --    10  --      10  --  10      --  10   10  --  10  --  12    --  12  --  00',
 '4  --  ai   乐子  --  乐子 ai    --  乐子 ai  --    乐子  --    乐子 ai  --  ai 画得  --    ai 画得  --  乐子  --  画得   ai  --  ai 画得  ',
 '5  --    开源  --  开源    --  开源   感谢  --  开源   开源  --    开源    --    感谢  --  感谢  --  开源  --    马斯克  --  马斯克',
 '6  --  视频    --  视频   视频  --    视频  --  生成 视频  --  做 视频  --  短 视频  --  视频 gpt  --  视频 ai 做  --  生 视频  --  短',
 '7  --    我超  --  我超  --      我超  --  天      --    我超    --  我超    --  天    --    天    --    天  --  布道  ',
 '8  --  3d  --  模型    --    模型  --  模型  --  建模  --  穿模  --    穿模  --  穿模    --    建模  --    穿模  ',
 '9  --  哈哈哈 哈哈哈  --    哈哈哈    --  哈哈哈   哈哈哈  --    哈哈哈哈    --    哈哈哈哈 哈哈哈  --  哈哈哈 哈哈哈 哈哈哈  --  哈哈哈   哈哈哈哈  --  哈哈哈哈 哈哈哈  --    哈哈哈哈  --  哈哈哈 哈哈哈  ',
 '10  --    机器人  --  机器人    --  机器人  --    机器  --  机器  --  机器人   机器人  --    机器人    --  管家  --  机器人 做  --  机器人   机器',
 '11  --  中国    --    中国    --    华为  --  华裔    --  china  --  华裔  --  华为    --  华为  --  china    --  中国   中国',
 '12  --    失业  --  失业    --  失业  --  失业   失业  --  劳动力  --  就业  --    翻译 失业  --  翻译 失业  --  工人  --    失业  ',
 '13  --    功能  --    能用    --  功能  --    没用  --    能用  --  用不起    --  用不起  --  能用    --  实用  --    没用  ',
 '14  --  价格  --  诈骗  --  骗  --    价格  --  诈骗    --  骗 投资  --    诈骗  --    钱  --  投资    --  投资',
 '15  --    假    --    假  --  假    --  真的假  --  假  --  真的    --    真的    --    真的假  --  假   假  --  真的假  ',
 '16  --  ➏  --  wc    --    wc    --  ➍  --  woc    --  ➏ ➏  --    woc    --  ➏ ➏ ➏  --    wc  --  wc',
 '17  --  人类   人类  --    人类  --  人类 之光    --  人类 之光  --  之光  --  之光    --  人类    --  消灭 人类  --  灭亡  --  消灭',
 '18  --  遥遥领先   遥遥领先  --    遥遥领先    --    遥遥领先  --  遥遥领先    --  遥遥领先 遥遥领先  --  遥遥领先  --    遥遥领先 遥遥领先  --  遥遥领先 遥遥领先 遥遥领先  --  遥遥领先 遥遥领先    --  遥遥领先   这才',
 '19  --  超梦  --  梦境  --  超梦    --    超梦  --    超梦    --  梦境    --  梦  --    梦境  --  梦里  --  做梦',
 '20  --  玩  --  游戏  --  好玩  --  玩    --    玩  --  游戏    --  好玩    --  做 游戏  --    做 游戏  --  游戏   玩',
 '21  --  奥特曼  --    奥特曼  --  奥特曼    --    奥特曼    --  奥特曼   奥特曼  --  奥特曼 日本  --    奥特曼 日本  --  日本    --    曼哈顿  --  众所周知 奥特曼',
 '22  --  卧槽   卧槽  --    卧槽    --  卧槽    --    卧槽  --  卧槽  --  挖槽   卧槽  --  挖槽    --  挖槽  --    挖槽  --    挖槽  ',
 '23  --  科技    --    技术  --    科技  --  科技  --  核心 科技    --  核心 科技  --  技术  --  美帝 核心  --  美帝 核心 科技  --    美帝 核心',
 '24  --    糊  --    吹    --  吹    --  糊  --    糊    --    扯淡  --  赶紧  --    吹  --    扯淡    --  糊  ',
 '25  --    眼睛  --  追    --  眼睛  --  追  --    影子  --    一眼  --  眼睛    --    影子    --  一眼 假    --  影子',
 '26  --  演员  --  电影    --    演员  --  电影  --    演员 失业  --  演员 失业  --  拍电影  --  演员 失业    --  宝莱坞  --  演员  ',
 '27  --    好家伙    --  好家伙    --    好家伙  --  好家伙  --  好好 好好  --  好好  --    不错    --    好好  --    耶    --    好好  ',
 '28  --  幽默  --    幽默  --  幽默    --    幽默    --    笑  --  死   笑  --  笑 死    --    笑 死  --  死   幽默  --  笑 死',
 '29  --    小脑 发达  --  小脑 发达  --    小脑  --  发达    --  小脑  --  发达  --  小脑 发达    --  发达   小脑  --  接口  --  脑机 接口',
 '30  --  卧槽 卧槽  --    卧槽 卧槽  --  卧槽 卧槽    --  哔哩  --  卧槽 卧槽 卧槽  --    卧槽  --  卧槽  --  卧槽    --  哔哩 干杯  --    卧',
 '31  --  吓人  --  吓人    --  恐怖    --  太 恐怖    --  太 恐怖  --    太 恐怖  --  恐怖  --    吓人  --    吓人    --  恐怖片',
 '32  --    国内    --  国内    --  地区  --  地区    --  国内   国内  --  地区   国内  --  国产    --  消息    --  国产   国内  --    国产  ',
 '33  --    不行    --    不行  --  把脉 针灸    --    ai 学  --      我试  --  把脉 针灸  --  中医 把脉 针灸  --  把脉  --  好像 行  --  针灸  ',
 '34  --    未来  --  未来  --  未来 已来  --  已来  --  已来    --  未来 已来    --    未来 已来  --  未来    --  已来   未来  --    未来  ',
 '35  --  自主 研发  --  自主 研发    --  抄袭  --  研发    --  自主  --    自主 研发  --  研发  --    自主  --  专利  --    抄袭',
 '36  --  苹果  --    苹果  --  苹果    --  乔布斯  --    乔布斯  --  xr  --  苹果 xr    --  苹果 xr  --    苹果 xr  --  xr  ',
 '37  --  宇宙  --  元 宇宙  --    元 宇宙  --    元  --  元  --  宇宙    --  元 宇宙    --  多重 宇宙  --  宇宙   元  --  空间',
 '38  --  脚  --  腿  --    脚  --  左脚  --    腿  --  腿    --  右脚  --    左脚  --  脚    --    四条',
 '39  --    数据  --  数据    --  数据  --  数据   数据  --  服务器  --  信息  --  本来 无用  --  杀熟    --  数据 清洗  --  数据分析',
 '40  --  虚拟  --  虚拟现实  --    虚拟  --    虚拟现实  --  虚拟世界  --  虚幻  --  形象  --  现实    --  虚拟 现实    --  虚拟 现实',
 '41  --    速度  --  速度  --  亿倍  --    亿倍  --  亿倍 速  --    亿倍 速  --  速  --  速度    --  加速  --    速度  ',
 '42  --  编程  --    程序员  --  程序员  --    编程  --  程序  --    程序  --  程序员    --    插件  --  软件  --  程序员 末日  ',
 '43  --  狗  --    狗  --  狗    --  神韵  --  doge    --  doge  --  狗警  --  狗警    --  狗 眼神  --    狗叫',
 '44  --  猫  --  猫猫  --    猫  --  猫猫    --    猫猫  --  喵  --  猫    --  猫娘  --  喵    --  猫   猫',
 '45  --  眼镜  --  眼镜    --    黑镜  --  黑镜  --  反光  --  黑镜    --    黑镜    --    眼镜  --    运镜    --  vr 眼镜',
 '46  --  谷歌  --    谷歌  --  谷歌    --  google  --  谷歌   谷歌  --    google  --    谷歌    --    谷歌 确实  --  ai   谷歌  --  谷歌 确实',
 '47  --  炸裂  --  炸裂    --    炸裂  --    炸裂    --  王炸  --  炸裂   炸裂  --  爆炸  --  炸  --  王炸    --    炸',
 '48  --    赛博  --  赛博  --  耶稣  --  赛博 耶稣  --  赛博    --  赛博 耶稣    --  赛博 飞升    --  赛博 飞升  --  耶稣    --    赛博 算命',
 '49  --  中餐  --    中餐  --  中餐    --  洗碗  --    洗碗  --    中餐    --  洗手  --  炒菜  --  洗手    --  做 中餐',
 '50  --    学废  --  学废  --  学废    --    学废    --  学废   学废  --    废腰  --    废腰    --  教培 完  --  废腰   学废  --  废腰  ',
 '51  --  666  --  666    --    666  --    666    --  666   666  --    66666    --    66666  --  66666    --  66666  --  666   66666',
 '52  --  微软  --    微软  --  微软    --    microsoft    --    这回 微软  --    花 q  --  microsoft  --    ibm  --  q 微软  --  这回 微软',
 '53  --  数学  --    算力  --  算法    --  算法  --  算力  --  数学 物理  --  充足  --  equation    --    equation  --  线性代数  ',
 '54  --    完    --    完  --  完   完  --  完    --    终于    --  终于    --  完  --    结束  --  结束  --    结束  ',
 '55  --  显卡  --    显卡  --  显卡    --  gpu  --  买 显卡  --  gpu    --  显卡   显卡  --  gpu 算力  --  主权    --  买 显卡  ',
 '56  --  世界   世界  --  改变    --    世界  --  改 做    --    世界    --    改变    --    世界 改变  --  全球 变暖  --    世界 要变  --  世界 要变',
 '57  --    逆天    --    逆天  --  逆天   逆天  --  逆天    --  逆天  --  文艺复兴   车  --  文艺复兴  --  逆天   做  --  面   逆天  --  复古   自动',
 '58  --  孩子    --  孩子  --  能生  --  帮 抢  --    能生 孩子  --    能生  --  能生 孩子  --  能生 孩子    --  飞机    --    帮',
 '59  --    西部  --    西部 世界  --  西部 世界  --  西部 世界    --  西部  --  世界   西部  --  世界    --  西部 世界 bgm  --  世界 bgm  --  世界 bgm  ',
 '60  --  画师  --  艺术  --    画师  --  艺术家  --  画手  --  艺术 价值  --  价值    --  价值  --  ai 手  --  说 画师',
 '61  --    太强  --    太强    --  太强  --  太强    --  太强   太强  --  强大  --    强    --    强  --    强大  --  强大  ',
 '62  --  100%  --  100%    --    0%  --    0%    --    100%    --  0%  --    100%  --  0%    --  高 40%  --  40%',
 '63  --  老马  --    老马  --  马  --    马  --  马    --  抓马  --    这踏马 入侵  --  这踏马 入侵  --  马陷 地里  --  这踏马 入侵 现实',
 '64  --    效果  --  特效  --  效果  --    特效  --  效果    --  效果   效果  --  特效    --  五毛  --  毛钱 特效 感觉  --  特效 好烂',
 '65  --  一年  --  10 年    --  10 年  --  年    --  七年    --  再过  --    一年  --  一年 前  --  想想  --  想想 一年',
 '66  --  文字  --    文字  --  文字    --    文字    --  汉字  --  严谨  --  鬼画符    --  鬼画符  --    鬼画符  --    鬼画符  ',
 '67  --    三体  --  三体  --    三体    --  三体    --  三体   三体  --  折叠  --    折叠  --  吵爷    --  小鬼 退散    --  小鬼 退散',
 '68  --    可爱    --    可爱  --  可爱    --  可爱  --  漂亮  --  漂亮    --  可爱   可爱  --    漂亮  --  太美    --  太美',
 '69  --  螃蟹  --    螃蟹  --  蟹  --  章鱼  --  鱼  --  螃蟹 腿  --    螃蟹 腿  --  蟹    --  鱼    --  厚礼 蟹  ',
 '70  --  老黄  --    老黄  --    黄油  --  黄油  --  黄    --  黄色  --  大黄  --  黄  --    黄色  --    大黄',
 '71  --    训练  --  训练  --  训练    --  推特 训练  --    推特 训练  --    推特  --  推特  --  等于 训练  --  运行 等于 训练  --  训练   运行',
 '72  --    文言  --  文言  --  文言 一心  --    文言 一心  --  一心  --  文言 一心    --  一心    --    文心  --    文心 言  --  一心   文言',
 '73  --  nb   nb  --    nb    --    nb  --  nb    --  nb  --  b   nb  --    b    --    n  --  b    --    niu',
 '74  --  手指  --    手臂  --  手臂  --    手指  --  手  --  手是  --    手臂 肌肉  --  手臂 肌肉  --    手是  --    手',
 '75  --  协同  --    协同  --  协同    --    协同    --  协同   协同  --  拟合    --    拟合    --    拟合  --    同传  --  拟合',
 '76  --  bing   bing  --    bing    --  bing    --    bing  --  bing  --  lens   谷歌  --  lens    --  lens  --  google   lens  --  bing   google',
 '77  --  透明 背景  --    透明 背景  --  sd 渲染 稳定  --    摄影  --  渲染 稳定  --  完   摄影  --  透明  --  稳定  --  画质  --  sd 渲染',
 '78  --  需求 强行 创造  --  付费   人少  --  赶紧 民用化 特别  --  c 挺  --  赶紧 民用化  --    人少  --  言   需求  --  真的 无穷 个小亮  --  无穷 个小亮  --  创造 需求',
 '79  --    好看  --  好看    --  好看  --    好看    --  好看   好看  --    看着  --    手    --  看着  --  一眼      --  倒回去',
 '80  --  刀  --  刀剑  --  刀剑 神域  --  神域  --    刀剑 神域  --    刀剑  --  刀    --  200 刀  --  刀剑 神域    --  神域  ',
 '81  --  性格    --  性格  --  不太  --    gpt  --  gpt   gpt  --    gpt    --  插件  --  性格      --  太想    --  周末',
 '82  --  左下角  --    左下角  --  消失  --  楼梯  --  楼梯 消失  --  消失    --  走 走  --    踩  --  凭空出现    --    走 走',
 '83  --  magi    --  magi  --    magi  --    magi    --  magi   magi  --  魔法  --  魔法    --  魔幻  --    魔法  --  魔幻  ',
 '84  --  广告  --  宣传片  --  发抖  --  广告公司  --    广告  --  广告    --    广告公司  --  做广告  --  拍 广告    --  广告业',
 '85  --  套娃    --  套娃   套娃  --    套娃  --    套娃    --  套娃  --    可爱  --    可爱    --  可爱  --  可爱    --  可爱   可爱',
 '86  --  信    --    信    --  信  --    信  --  可靠    --  可靠  --    验证码  --  验证  --  验证码  --    不信',
 '87  --  老鼠  --    老鼠  --  老鼠 电影  --  视角  --  老鼠    --  高   老鼠  --  视角 老鼠  --    有没有 老鼠  --  盯 屏幕  --  屏幕  ',
 '88  --  恭喜  --    恭喜  --  恭喜    --  恭喜   恭喜  --  恭喜 恭喜  --    恭喜 恭喜  --  恭喜 恭喜    --    恭喜    --  恭喜 老婆  --  happyhappy  ',
 '89  --    蜥蜴人  --    蜥蜴人    --  蜥蜴人    --  蜥蜴人   蜥蜴人  --  蜥蜴人  --  人格    --  人格  --  负责人   g7  --  加 舔食  --  负责人  ',
 '90  --  隐私  --  隐私    --    隐私  --  隐私   隐私  --  保护 私密性  --  私密性  --    保护 私密性  --  秘密  --    保护  --  私密性  ',
 '91  --  万岁    --  娜  --  李姐 万岁    --  李姐 万岁  --  李姐  --  万岁  --  蛋    --    李姐  --    李姐 万岁  --  蛋',
 '92  --    太好了    --  太好了    --  两个 概念    --    真不错  --      真不错  --    两个 概念  --      好事  --  真不错      --  這個      --    好事  ',
 '93  --  回放  --    定义  --  定义  --    回放  --    灵气  --  复苏    --  复苏  --    灵气 复苏  --  回放    --  灵气 复苏  ',
 '94  --  4090  --    4090  --  3090  --    3090  --  散  --  4080  --  3090   3090  --  3090    --  行不行    --  行不行',
 '95  --  聊 做    --  不算    --  尬 聊 做  --  只会 两个 ai  --  只会 两个  --  做   引导  --  两个 ai 尬  --  聊 做  --  不耐烦   不算  --  不耐烦',
 '96  --    控制  --  控制 核武器  --  控制 核武器    --    控制 核武器  --  核武器   控制  --  核武器    --  核武器  --  能源   控制  --  控制 能源  --    控制 能源',
 '97  --  metaxr    --  metaxr  --    metaxr  --    metaxr    --  metaxr   metaxr  --  rtx  --    on  --  on  --  rtx   on  --  rtx  ',
 '98  --  亿  --  亿    --    5000 亿  --  5000 亿  --  万块  --  万 人民币  --    5000  --  5000  --  万  --  人民币',
 '99  --    半斤八两  --  半斤八两    --  半斤八两  --    半斤八两    --  八两 半斤  --  半斤    --  半斤八两   半斤八两  --    八两 半斤  --    八两  --  八两',
 '100  --  飞升   机械  --    机械 飞升  --  机械 飞升  --  机械 飞升    --  飞升  --    机械  --  飞升    --  机械  --  血肉 苦弱 机械  --  消失   肉体',
 '101  --    学会    --  学会   学会  --  学会    --    学会  --  学会  --  学习   学会  --    深度 学习  --    深度  --  学习    --  深度 学习',
 '102  --    马斯克    --  马斯克   马斯克  --  马斯克    --    马斯克  --    mark    --  mark    --  mark   chen  --    mark  --  mark  --    chen  ',
 '103  --  捂脸    --  捂脸  --  嘴  --  嘴型    --  嘴型  --  ￢  --    嘴型    --    嘴型  --  张嘴    --  脸红',
 '104  --  贾  --  贾 维斯  --  维斯  --    贾  --    贾 维斯  --  贾 维斯    --  维斯    --  维斯   贾  --  钢铁 侠 贾  --  侠 贾',
 '105  --  养老  --    养老  --    ai 养老  --  ai 养老  --  ai 养老 时代  --    养老    --      养老  --  养老 时代  --  养老    --  老人',
 '106  --  真实   真实  --    真实    --    真实  --  真实    --  真实  --    真的    --    真    --  真实   真的  --    够 真实  --  真的   真的',
 '107  --    closeai  --    closeai    --  closeai  --  closeai    --  closeai   closeai  --    封进    --    封进  --  封进    --  封进  --  close  ',
 '108  --  丸辣  --    丸辣  --  丸辣    --    丸辣    --  丸辣   丸辣  --  药丸 辣  --  药丸  --    丸辣 ai  --    完辣    --    完辣',
 '109  --  买    --  买  --  国内 买  --    买  --  买不起  --  买不起    --  买不到  --  账号  --  啥时候 随便  --  啥时候 随便 买',
 '110  --    卷  --  卷  --  卷    --    卷    --  卷   卷  --  卷 卷  --  卷 死  --  卷 卷    --    卷 卷  --  ai 卷',
 '111  --  卡  --  卡    --  n 卡  --  买点  --  卡   卡  --  卡   翻译  --  meta 少  --    卡  --  买 卡    --  买点 卡',
 '112  --    太酷    --  太酷    --  太酷  --    太酷  --    太棒了    --    太棒了  --  太棒了    --  太棒了  --  太酷   太棒了  --  太棒了   太酷',
 '113  --  版本  --  初代  --    初代  --  初代    --    第一代  --  1.0  --  初代 牛  --  这是 初代  --  这是 初代    --  1.0 版本',
 '114  --  聪明   聪明  --    聪明    --    聪明  --  聪明    --  聪明  --  几都   聪明  --  几都  --  人才   真的  --  contana  --    真的 天才',
 '115  --  霍金  --    霍金  --  哈利波 特  --    哈利波  --    哈利波 特  --  哈利波  --  青春 版  --  青春  --  青春 版    --  版   霍金',
 '116  --    见证  --    见证 历史  --  见证 历史  --  历史    --  见证 历史    --  历史  --  见证  --  历史   见证  --  载入史册  --  载入史册  ',
 '117  --  工具    --  工具  --    工具  --    工具    --  工具 生命    --  共情  --  生命 个体  --  包 饺子  --  工具   工具  --  工具 生命',
 '118  --    印度人  --  印度人  --  印度人    --  印度人   印度人  --    印度人    --    印度  --  印度  --  印度   印度  --  印度    --  太 估计',
 '119  --    茅台    --  茅台    --    茅台  --  盘古    --  茅台  --  比亚迪  --    盘古    --  茅台   茅台  --    盘古  --  盘古',
 '120  --  黑客帝国  --    黑客帝国  --  黑客帝国    --    黑客帝国    --  黑客帝国   黑客帝国  --  黑客帝国 不远  --    黑客帝国 不远  --  黑客帝国 不远    --  成 真  --  帝国  ',
 '121  --  杯子  --  杯底  --  咖啡  --  擦 杯底  --  抹布  --  底  --  杯子 底  --    杯子  --  擦  --  杯',
 '122  --    免费  --  免费  --  免費    --  免費  --  免费    --    免费    --  免费   免费  --  免费 挺  --  全世界 北 韩国  --  帮 训练',
 '123  --    生快    --  生快    --  生快  --    生快  --  生快   生快  --      sd  --  生快   死  --  sd   生快  --    sd    --  真    ',
 '124  --    --    --    --    --    --    --    --    --    --  ',
 '125  --  朋克  --  赛博 朋克  --    赛博 朋克  --  朋克    --  朋克 2077  --  赛博 朋克 2077  --  赛博 朋克    --  2077   赛博  --  朋克 2077    --  2077  ',
 '126  --  意大利  --    意大利  --  意大利人  --  意大利人    --    意大利人    --    意大利人  --  原型 意大利 南部  --  意大利 南部  --  南部  --  原型 意大利',
 '127  --  版权  --  adobe  --  版权    --    版权  --    版权    --  版权   adobe  --  素材 版权  --  网易  --    adobe  --  盗版',
 '128  --    记得    --  记得    --  记得   记得  --    记得  --  记得  --  初心    --  初心  --    记忆  --  忘  --  记忆 星神',
 '129  --  抢票  --  抢票    --    抢票  --    抢票    --  抢票   抢票  --  抢票   投票  --  投票   抢票  --  投票    --    投票    --    投票',
 '130  --  比例  --    比例  --  比例    --  比例   比例  --    比例    --  人车  --  比例 不太对    --  比例 不太对  --    人车 比例  --    人车',
 '131  --  预测  --    预测  --  验证  --  预测 验证  --  预测 检测  --  预期    --  预测 a  --    预测 a  --    预测 验证  --  验证  ',
 '132  --  支持   支持  --    支持    --  支持    --    支持  --  支持  --    大力支持    --  支持      --  大力支持    --    大力支持  --  大力支持',
 '133  --    日本  --  日本  --    日本 走  --  日本 走  --  赌  --  半导体  --  日本 聪明  --    日本 聪明  --  发达国家  --  抓住',
 '134  --  进化  --  进化    --  人类 进化  --  外部 竞赛 进化  --  竞赛  --  光荣 进化    --  光荣 进化  --  光荣  --    外部 竞赛  --  进化   外部',
 '135  --    2024  --  2024  --    2077  --  2025  --  2077  --  2025    --    2025  --    2025    --    2077    --  2077  ',
 '136  --  想要    --      太  --    我要    --  我要    --    太    --  太    --  分镜    --  太      --  够   太棒了  --  陶',
 '137  --  灵魂  --    灵魂  --    搜魂  --  搜魂  --  灵魂    --    搜魂    --  搜魂    --    灵魂    --  机魂  --  机魂  ',
 '138  --    agi    --  agi    --  agi   agi  --    agi  --  agi  --  agi 到来  --  筛选   tgdkgdgdsdazpdidkbokvrevlaoanghd  --  ame  --  ame 波高  --  ame 波高  ',
 '139  --  机动队  --  攻  --    攻  --    攻壳  --  雷击  --  开幕 雷击  --  开幕 雷击    --  雷击    --    弹幕    --    弹幕',
 '140  --  担心    --  危险  --  好事   ai  --  强 爆发    --  口子 早晚  --  口子 早晚 强  --  局长 董事会    --  在乎  --  团队 内部  --  团队 内部 gpt',
 '141  --    d    --  d    --    d  --  ai   ai  --  d  --  aiy   e  --  e 宝  --    yo  --    ou  --  接 ai  ',
 '142  --  绵绵  --  糖    --  绵绵 糖  --  绵绵 糖    --    天空 绵绵  --    天空  --  天空 绵绵 糖  --  天空 绵绵  --  糖  --  天空',
 '143  --  伟达  --  英  --  英 伟达  --    英 伟达  --    英  --  英 伟达    --  伟达    --  伟达   英  --  斯   冷  --  没买英',
 '144  --  次    --  次  --  50 次    --  50 次  --    50 次  --    50  --  50  --  次   50  --  次   网上  --  早就 迈入 次',
 '145  --  字幕  --  英语  --  英语    --    字幕  --  听不懂  --    英语  --  字幕 漏掉 字  --  来学 英语 话  --  差评   寻思  --  字幕 漏掉',
 '146  --  细节    --    细节  --  细节  --  细节   细节  --    细节    --  手部 细节    --  难度 短期内  --  细节   抠  --  抠 细节 真的  --  难度 短期内 很难',
 '147  --  水獭  --    水獭  --  ta    --  水獭 ta  --  枯 山水  --  水獭    --    水獭 ta  --  枯  --  水獭 ta    --  山水',
 '148  --    无敌  --    无敌    --  无敌   无敌  --  无敌    --  无敌  --  天敌  --  实体 体验  --  无敌   女人  --  那真 无敌    --  实体 体验 那真',
 '149  --  gpt4   gpt4  --    gpt4    --  gpt4    --    gpt4  --  gpt4   gpt3.5  --    gpt3.5  --    gpt3.5    --    gpt40  --  gpt40  --  dlss4',
 '150  --  键  --  键盘  --  alt  --  windows 键  --    替换  --  替换  --  按钮  --  占用  --  ctrl  --  windows',
 '151  --  花    --  花  --    花    --  喝彩  --  宝 花  --  花   花  --  宝 花    --    花  --    宝 花  --  宝们 花  ',
 '152  --  懂王  --    懂王  --  懂 王胜  --  王胜  --  汪汪  --  王  --  林皇    --  打钱   懂  --  帝皇  --  懂王 附体  ',
 '153  --  军事  --  军用  --    军用  --    美军  --  军事    --    用于 军事  --  用途    --  美军  --  用于 军事  --  用途',
 '154  --  泰裤  --  泰裤 辣  --    泰裤  --    泰裤 辣  --  泰裤 辣    --  辣   泰裤  --  辣    --  辣  --  拉   咖喱  --  真的 泰裤 拉',
 '155  --  动画    --  动画  --  做 动画  --    做 动画  --  做 动画    --    动画  --  动画   做  --  动画片    --  动画片  --  图片 p 动画',
 '156  --    绷 不住  --  不住   绷  --    绷  --  绷 不住  --  不住  --  绷 不住    --  不住    --  绷  --  绷住  --  绷住  ',
 '157  --    环  --  环  --    环 大陆  --  环 大陆  --  大陆   环  --  环 大陆    --  大陆    --  大陆  --  大陆 更新    --  大陆 发布',
 '158  --  恐怖 谷  --    恐怖 谷  --  谷  --  效应  --  效应 犯  --  效应 犯    --    恐怖  --  恐怖 谷 效应  --  谷 效应  --  犯  ',
 '159  --  giga    --  giga   giga  --    giga    --  giga  --    giga  --  5g   128g  --  128g   giga  --  128g    --  128g  --    128g  ',
 '160  --    太假  --    太假    --  太假   太假  --  太假    --  太假  --    尊嘟  --    好假  --    好假    --  好假    --  难度   太假',
 '161  --  震惊    --    震惊    --  震惊  --    震惊  --  震惊   震惊  --  奇怪  --  震惊   c  --  点 爆发  --  震惊   混入  --  震惊   真的',
 '162  --  黑人  --    黑人  --  太 正确  --  黑人    --  黑人 太  --  黑人 太 正确  --  黑 女儿  --  太 正确    --  形象 黑人 太  --    形象',
 '163  --  5g  --  5g    --    5g  --    5g    --  5g   5g  --  华为 5g  --  华为 5g    --  记不太清 好像  --  鉴定  --  感觉 5g',
 '164  --  敬酒  --  生产队 驴  --  敬酒    --  生产队  --  驴  --  白酒  --    生产队 驴  --  坐    --    生产队  --  坐',
 '165  --  这下 懂  --  理解万岁  --  这下 懂    --  看不懂    --    懂  --  看不懂  --  懂  --  懂 太典 hhh  --  懂 米莱  --  话   懂',
 '166  --    聊过    --  聊过  --  聊过    --    聊过  --  无语子    --  礼貌 文心 言  --  讲人话   说话  --  语 一眼  --  语   说人话  --  喱 语',
 '167  --  透视  --  透视    --    透视  --    透视    --  重叠 透视 好大  --  脚出   透视  --  透视   透视  --  透视   这块  --  好像   透视  --  透视   解决',
 '168  --  人口老龄化  --    人口老龄化  --    人口老龄化    --  人口老龄化    --  人口老龄化   人口老龄化  --    少 美国  --  老龄化 影响 年轻人  --  中年人 头像    --    老龄化  --  老龄化 影响',
 '169  --    科幻  --  科幻小说  --  科幻片    --  科幻电影  --  科幻片  --  科幻  --  科幻    --  科幻   科幻电影  --    科幻    --  拍 科幻电影',
 '170  --  墙  --  防火墙  --    防火墙  --  毛线  --  拆    --  墙 建    --  墙 内用    --  墙 内用  --  我会 出手  --  墙 建',
 '171  --    宰 驴  --  宰 驴  --  cpu 烧    --  cpu 烧  --  宰 驴    --    宰  --    cpu 烧  --    cpu  --      宰  --      cpu',
 '172  --  猴子  --  猴子    --    猴子  --  水 猴子  --  水 猴子    --  猿声 啼  --  猴子   小亮  --  啼 不住    --  啼 不住  --  啼',
 '173  --  新闻  --  假新闻  --    假新闻  --  假新闻    --    假新闻    --  担心 新闻  --  假冒  --    新闻  --  造假    --  新闻 早就',
 '174  --  父子 局  --    父子 局  --  父子 局    --  局    --  局  --  父子  --    父子  --  这人  --    这人  --  mira  ',

In [ ]:
topic_model.save('last_bertopic.model')

# Exploration des prédictions du modèles

In [ ]:
topic_model = BERTopic.load('last_bertopic.model')

In [18]:
# topics_to_merge = [[3,4,6],[3,15]]
# topic_model.merge_topics(docs, topics_to_merge)

barchart = topic_model.visualize_barchart(top_n_topics=17, title="Représentation des topics", width=400, n_words=7)
barchart.write_html('barchart.html')

In [ ]:
topic_labels_dict = {
    0:"L'opinion & le journalisme",
    1:"Financement & l'indépendance des médias",
    2:"Désinformation"
}

topic_model.set_topic_labels(topic_labels_dict)
barchart = topic_model.visualize_barchart(top_n_topics=17, custom_labels=True, title="Représentation des topics<", width=800, n_words=7)
barchart.write_html('barchart.html')

In [19]:
hierarchical_topics = topic_model.hierarchical_topics(docs)
tree = topic_model.get_topic_tree(hierarchical_topics)
tree

100%|██████████| 343/343 [00:00<00:00, 445.51it/s]

'.\n├─厉害   厉害_  厉害  _  厉害_  太 厉害_太 厉害  \n│    ├─■──  太 厉害_太 厉害  _太 厉害_厉害   太_厉害   太大 ── Topic: 255\n│    └─厉害   厉害_  厉害  _  厉害_厉害  _厉害\n│         ├─■──厉害   太_  猛  _太强   猛_猛   厉害_厉害   好强 ── Topic: 251\n│         └─■──厉害   厉害_  厉害  _  厉害_厉害  _厉害 ── Topic: 205\n└─遥遥领先   遥遥领先_  声音_逼   牛_  赛博_奥特曼\n     ├─遥遥领先   遥遥领先_  声音_逼   牛_  赛博_奥特曼\n     │    ├─  nb  _nb   nb_  nb_nb  _nb\n     │    │    ├─■──nb   nb_  nb  _  nb_nb  _nb ── Topic: 73\n     │    │    └─■──  nb  _装修 nha_纽毕_nha   nb_nha   ── Topic: 306\n     │    └─遥遥领先   遥遥领先_  声音_逼   牛_  赛博_奥特曼\n     │         ├─遥遥领先   遥遥领先_  声音_逼   牛_  赛博_奥特曼\n     │         │    ├─机械 飞升_机械 飞升  _  机械 飞升_飞升   机械_飞升\n     │         │    │    ├─■──飞升   机械_  机械 飞升_机械 飞升_机械 飞升  _飞升 ── Topic: 100\n     │         │    │    └─■──机械 飞升  _机械 飞升_飞升  _瓢治能 机器_  1%   ── Topic: 312\n     │         │    └─遥遥领先   遥遥领先_  声音_逼   牛_  赛博_奥特曼\n     │         │         ├─遥遥领先   遥遥领先_  声音_逼   牛_  赛博_奥特曼\n     │         │         │    ├─和平_和平 和平_改 做_本质  _改\n     │         │         │    │    ├─和平_和平 和平_  和平_和平 和平 和平_和平 和平  \n     │         │         │    │    │    ├─■──和平 和平_和平_和平 和平 和平_  和平 和平_和平 和平   ── Topic: 257\n     │         │         │    │    │    └─■──颗 核弹 国际_概念 改 做_250_全方位 本质_做 产物 全方位 ── Topic: 304\n     │         │         │    │    └─转换 改_转换 改 做_转换_超越 本质_超越 本质  \n     │         │         │    │         ├─转换 改 做_转换 改_转换_超越 本质  _超越 本质\n     │         │         │    │         │    ├─■──超越 本质  _超越 本质_改 做 超越_做 超越_做 超越 本质 ── Topic: 240\n     │         │         │    │         │    └─■──  of  _  of_of_of  _round ── Topic: 295\n     │         │         │    │         └─■──工业革命_工业革命  _革命_科技 革命_第四次 ── Topic: 231\n     │         │         │    └─遥遥领先   遥遥领先_  声音_逼   牛_  赛博_奥特曼\n     │         │         │         ├─遥遥领先   遥遥领先_  声音_逼   牛_  赛博_奥特曼\n     │         │         │         │    ├─遥遥领先   遥遥领先_  声音_逼   牛_  赛博_奥特曼\n     │         │         │         │    │    ├─  可爱_  可爱  _可爱  _可爱_可爱   可爱\n     │         │         │         │    │    │    ├─  可爱_  可爱  _可爱  _可爱_可爱   可爱\n     │         │         │         │    │    │    │    ├─■──  可爱  _  可爱_可爱  _可爱_漂亮 ── Topic: 68\n     │         │         │         │    │    │    │    └─■──套娃  _套娃   套娃_  套娃_  套娃  _套娃 ── Topic: 85\n     │         │         │         │    │    │    └─星球大战_  忽悠_  星球大战_  忽悠  _忽悠  \n     │         │         │         │    │    │         ├─葛 大爷_大爷_葛_李姐 万岁  _蛋  \n     │         │         │         │    │    │         │    ├─■──万岁  _娜_李姐 万岁  _李姐 万岁_李姐 ── Topic: 91\n     │         │         │         │    │    │         │    └─■──葛 大爷_葛_大爷_葛 大爷 哈哈哈_喷   点 ── Topic: 341\n     │         │         │         │    │    │         └─星球大战_  忽悠  _忽悠  _  星球大战_  忽悠\n     │         │         │         │    │    │              ├─■──  道观  _觉  _道观  _道观_  觉 ── Topic: 271\n     │         │         │         │    │    │              └─■──星球大战_  星球大战_怀疑   星球大战_  星球大战 幸存者_  星球大战   ── Topic: 334\n     │         │         │         │    │    └─遥遥领先   遥遥领先_  声音_逼   牛_  赛博_奥特曼\n     │         │         │         │    │         ├─遥遥领先   遥遥领先_  声音_逼   牛_  赛博_奥特曼\n     │         │         │         │    │         │    ├─卧槽   卧槽_  卧槽  _哈哈哈 哈哈哈_卧槽  _哈哈哈   哈哈哈\n     │         │         │         │    │         │    │    ├─卧槽   卧槽_  卧槽  _卧槽  _  卧槽_卧槽 卧槽\n     │         │         │         │    │         │    │    │    ├─■──卧槽   卧槽_  卧槽  _卧槽  _  卧槽_卧槽 ── Topic: 22\n     │         │         │         │    │         │    │    │    └─■──卧槽 卧槽_  卧槽 卧槽_卧槽 卧槽  _哔哩_卧槽 卧槽 卧槽 ── Topic: 30\n     │         │         │         │    │         │    │    └─哈哈哈 哈哈哈_哈哈哈   哈哈哈_  哈哈哈  _哈哈哈 哈哈哈  _  哈哈哈哈  \n     │         │         │         │    │         │    │         ├─  恐怖_恐怖 谷_恐怖_  恐怖 谷_谷\n     │         │         │         │    │         │    │         │    ├─■──吓人_吓人  _恐怖  _太 恐怖  _太 恐怖 ── Topic: 31\n     │         │         │         │    │         │    │         │    └─■──恐怖 谷_  恐怖 谷_谷_效应_效应 犯 ── Topic: 158\n     │         │         │         │    │         │    │         └─哈哈哈 哈哈哈_哈哈哈   哈哈哈_  哈哈哈  _哈哈哈哈 哈哈哈_  哈哈哈哈  \n     │         │         │         │    │         │    │              ├─哈哈哈 哈哈哈_哈哈哈   哈哈哈_  哈哈哈  _哈哈哈哈 哈哈哈_哈哈哈 哈哈哈  \n     │         │         │         │    │         │    │              │    ├─■──机动队_攻_  攻_  攻壳_雷击 ── Topic: 139\n     │         │         │         │    │         │    │              │    └─哈哈哈 哈哈哈_哈哈哈   哈哈哈_  哈哈哈  _哈哈哈哈 哈哈哈_  哈哈哈哈  \n     │         │         │         │    │         │    │              │         ├─■──比尔盖茨_  比尔盖茨_小扎_  小扎_忙   比尔盖茨 ── Topic: 254\n     │         │         │         │    │         │    │              │         └─哈哈哈 哈哈哈_哈哈哈   哈哈哈_  哈哈哈  _哈哈哈哈 哈哈哈_  哈哈哈哈  \n     │         │         │         │    │         │    │              │              ├─■──  绷 不住_不住   绷_  绷_绷 不住_不住 ── Topic: 156\n     │         │         │         │    │         │    │              │              └─■──哈哈哈 哈哈哈_  哈哈哈  _哈哈哈   哈哈哈_  哈哈哈哈  _  哈哈哈哈 哈哈哈 ── Topic: 9\n     │         │         │         │    │         │    │              └─➏_  wc  _wc  _➍_woc  \n     │         │         │         │    │         │    │                   ├─■──➏_wc  _  wc  _➍_woc   ── Topic: 16\n     │         │         │         │    │         │    │                   └─■──片   嚯_舵机  _舵机_纸 片  _纸 片 ── Topic: 337\n     │         │         │         │    │         │    └─遥遥领先   遥遥领先_  声音_逼   牛_  赛博_奥特曼\n     │         │         │         │    │         │         ├─遥遥领先   遥遥领先_逼   牛_学废_  学废_  学废  \n     │         │         │         │    │         │         │    ├─花  _花_新年快乐_拜个 年_拜个\n     │         │         │         │    │         │         │    │    ├─新年快乐_新年快乐  _  新年快乐_  新年快乐  _新年快乐   新年快乐\n     │         │         │         │    │         │         │    │    │    ├─■──谢_厚礼 谢_厚礼_  谢谢_产品 哥   ── Topic: 294\n     │         │         │         │    │         │         │    │    │    └─■──新年快乐  _新年快乐_  新年快乐  _  新年快乐_新年快乐   新年快乐 ── Topic: 309\n     │         │         │         │    │         │         │    │    └─花  _花_拜个 年_拜个_  拜个 年\n     │         │         │         │    │         │         │    │         ├─■──花  _花_  花  _喝彩_宝 花 ── Topic: 151\n     │         │         │         │    │         │         │    │         └─■──拜个_拜个 年_  拜个_  拜个 年_花   拜个 ── Topic: 237\n     │         │         │         │    │         │         │    └─遥遥领先   遥遥领先_逼   牛_  学废_学废_  学废  \n     │         │         │         │    │         │         │         ├─  赛博_赛博_超梦_梦境_朋克\n     │         │         │         │    │         │         │         │    ├─生命_数字 生命_下载_下载  _  数字 生命\n     │         │         │         │    │         │         │         │    │    ├─下载_下载  _生命_  下载  _  下载\n     │         │         │         │    │         │         │         │    │    │    ├─生命_工具  _工具_硅基_碳基\n     │         │         │         │    │         │         │         │    │    │    │    ├─■──工具  _工具_  工具_  工具  _工具 生命   ── Topic: 117\n     │         │         │         │    │         │         │         │    │    │    │    └─■──硅基_碳基_  硅基_生物学_  碳基 ── Topic: 219\n     │         │         │         │    │         │         │         │    │    │    └─下载  _下载_  下载_  下载  _下载   下载\n     │         │         │         │    │         │         │         │    │    │         ├─■──完整_完整 生命  _完整 生命_完整 一生_  我要 ── Topic: 282\n     │         │         │         │    │         │         │         │    │    │         └─■──下载_下载  _  下载_  下载  _下载   下载 ── Topic: 226\n     │         │         │         │    │         │         │         │    │    └─数字 生命_  数字 生命_数字_启动_生命 启动\n     │         │         │         │    │         │         │         │    │         ├─■──数字 生命_  数字 生命_数字_数字 生命 启动_生命 启动 ── Topic: 193\n     │         │         │         │    │         │         │         │    │         └─■──源神_源神 启动_  源神_启动_启动   ── Topic: 340\n     │         │         │         │    │         │         │         │    └─  赛博_赛博_超梦_朋克_梦境\n     │         │         │         │    │         │         │         │         ├─黑客帝国_刀_  赛博_  黑客帝国_刀剑\n     │         │         │         │    │         │         │         │         │    ├─刀_刀剑_神域_刀剑 神域_  刀剑 神域\n     │         │         │         │    │         │         │         │         │    │    ├─■──刀_刀剑_刀剑 神域_神域_  刀剑 神域 ── Topic: 80\n     │         │         │         │    │         │         │         │         │    │    └─小克_呜呜  _小艺_半路 抱 走_想到 名字 dcmini\n     │         │         │         │    │         │         │         │         │    │         ├─■──小克_说   想到_名字 dcmini_  小艺_  小娜 ── Topic: 325\n     │         │         │         │    │         │         │         │         │    │         └─■──  上点_半路 抱 走_试一下_病毒 尝尝  _注入 电子 病毒 ── Topic: 256\n     │         │         │         │    │         │         │         │         │    └─黑客帝国_  赛博_  黑客帝国_赛博_黑客帝国  \n     │         │         │         │    │         │         │         │         │         ├─■──  赛博_赛博_耶稣_赛博 耶稣_赛博   ── Topic: 48\n     │         │         │         │    │         │         │         │         │         └─■──黑客帝国_  黑客帝国_黑客帝国  _  黑客帝国  _黑客帝国   黑客帝国 ── Topic: 120\n     │         │         │         │    │         │         │         │         └─超梦_朋克_梦境_超梦  _赛博 朋克\n     │         │         │         │    │         │         │         │              ├─■──超梦_梦境_超梦  _  超梦_  超梦   ── Topic: 19\n     │         │         │         │    │         │         │         │              └─朋克_赛博 朋克_  赛博 朋克_2077_2077  \n     │         │         │         │    │         │         │         │                   ├─■──朋克_赛博 朋克_  赛博 朋克_朋克  _朋克 2077 ── Topic: 125\n     │         │         │         │    │         │         │         │                   └─■──  2024_2024_  2077_2025_2077 ── Topic: 135\n     │         │         │         │    │         │         │         └─遥遥领先   遥遥领先_逼   牛_  学废_学废_  学废  \n     │         │         │         │    │         │         │              ├─遥遥领先   遥遥领先_逼   牛_学废_  学废_  学废  \n     │         │         │         │    │         │         │              │    ├─动画_  太强_  太强  _太强_太强  \n     │         │         │         │    │         │         │              │    │    ├─我草_我草  _  我草_  草_动物\n     │         │         │         │    │         │         │              │    │    │    ├─我草_我草  _  我草_  草_动物\n     │         │         │         │    │         │         │              │    │    │    │    ├─■──codeforces_解码   编码_下崗中   代码_碼工 下崗中_碼工 下崗中   ── Topic: 323\n     │         │         │         │    │         │         │              │    │    │    │    └─我草_我草  _  我草_动物_  我草  \n     │         │         │         │    │         │         │              │    │    │    │         ├─■──我草_我草  _  我草_  我草  _  草   ── Topic: 178\n     │         │         │         │    │         │         │              │    │    │    │         └─■──动物_动物 世界_  动物_动物 世界  _动物   ── Topic: 291\n     │         │         │         │    │         │         │              │    │    │    └─海浪_  海鸥_海鸥_  unbelievable_  unbelievable  \n     │         │         │         │    │         │         │              │    │    │         ├─■──  unbelievable  _不可思议  _unbelievable  _unbelievable_  unbelievable ── Topic: 324\n     │         │         │         │    │         │         │              │    │    │         └─■──海鸥_海浪_  海鸥_海浪 方向_  海浪 ── Topic: 252\n     │         │         │         │    │         │         │              │    │    └─动画_  太强_  太强  _太强_太强  \n     │         │         │         │    │         │         │              │    │         ├─  太强_  太强  _太强_太强  _太强   太强\n     │         │         │         │    │         │         │              │    │         │    ├─■──  毛发_毛发_毛发 效果_  毛发 效果_纹路 一致性 ── Topic: 311\n     │         │         │         │    │         │         │              │    │         │    └─■──  太强_  太强  _太强_太强  _太强   太强 ── Topic: 61\n     │         │         │         │    │         │         │              │    │         └─动画_动画  _  动画_做 动画_  做 动画\n     │         │         │         │    │         │         │              │    │              ├─■──动画  _动画_做 动画_  做 动画_做 动画   ── Topic: 155\n     │         │         │         │    │         │         │              │    │              └─■──动画_  动画_工作室 走 只会_赶工_走 只会 局部 ── Topic: 321\n     │         │         │         │    │         │         │              │    └─遥遥领先   遥遥领先_逼   牛_  学废_学废_学废  \n     │         │         │         │    │         │         │              │         ├─遥遥领先   遥遥领先_逼   牛_学废_  学废_学废  \n     │         │         │         │    │         │         │              │         │    ├─5g_  giga  _giga   giga_5g  _giga  \n     │         │         │         │    │         │         │              │         │    │    ├─5g_giga  _  giga  _giga   giga_5g  \n     │         │         │         │    │         │         │              │         │    │    │    ├─■──giga  _giga   giga_  giga  _giga_  giga ── Topic: 159\n     │         │         │         │    │         │         │              │         │    │    │    └─■──5g_5g  _  5g_  5g  _5g   5g ── Topic: 163\n     │         │         │         │    │         │         │              │         │    │    └─灵魂_欧姆_弥赛亚  _欧姆 弥赛亚_  赞美 欧姆\n     │         │         │         │    │         │         │              │         │    │         ├─欧姆_欧姆 弥赛亚  _弥赛亚_赞美 欧姆_欧姆 弥赛亚\n     │         │         │         │    │         │         │              │         │    │         │    ├─■──  茅台  _茅台  _  茅台_盘古  _茅台 ── Topic: 119\n     │         │         │         │    │         │         │              │         │    │         │    └─■──欧姆_  赞美 欧姆_弥赛亚  _赞美 欧姆_欧姆 弥赛亚   ── Topic: 184\n     │         │         │         │    │         │         │              │         │    │         └─灵魂_灵魂  _  灵魂_  搜魂_搜魂\n     │         │         │         │    │         │         │              │         │    │              ├─灵魂_灵魂  _  灵魂_搜魂_  搜魂\n     │         │         │         │    │         │         │              │         │    │              │    ├─■──牧师_灵魂_木得 灵魂_灵魂 西方人_视频 怪异 灵魂 ── Topic: 316\n     │         │         │         │    │         │         │              │         │    │              │    └─■──灵魂_  灵魂_  搜魂_搜魂_灵魂   ── Topic: 137\n     │         │         │         │    │         │         │              │         │    │              └─造神_真神_造神  _原神  _原神\n     │         │         │         │    │         │         │              │         │    │                   ├─■──真神_面相   神_神通  _神 與  _海灵   降世 ── Topic: 225\n     │         │         │         │    │         │         │              │         │    │                   └─■──宗教_女 想_帮 上帝 摘_舆论_毕设 ── Topic: 249\n     │         │         │         │    │         │         │              │         │    └─遥遥领先   遥遥领先_逼   牛_学废_  学废_学废  \n     │         │         │         │    │         │         │              │         │         ├─遥遥领先   遥遥领先_  遥遥领先  _  遥遥领先_文明_科技  \n     │         │         │         │    │         │         │              │         │         │    ├─  产品_产品_产品 画得_  产品 画得_产品 画得  \n     │         │         │         │    │         │         │              │         │         │    │    ├─■──蚊子_  蚊子_间谍 一只 苍蝇_终于 想_谴责   蚊子 ── Topic: 328\n     │         │         │         │    │         │         │              │         │         │    │    └─  产品_产品_产品 画得_  产品 画得_画得   产品\n     │         │         │         │    │         │         │              │         │         │    │         ├─■──  产品 画得_产品 画得_产品 画得  _画得   产品_  产品 ── Topic: 280\n     │         │         │         │    │         │         │              │         │         │    │         └─■──产品_  这才 做_这才 做_这才 做 产品_新 产品 ── Topic: 197\n     │         │         │         │    │         │         │              │         │         │    └─遥遥领先   遥遥领先_  遥遥领先  _  遥遥领先_文明_科技  \n     │         │         │         │    │         │         │              │         │         │         ├─遥遥领先   遥遥领先_  遥遥领先  _  遥遥领先_文明_科技  \n     │         │         │         │    │         │         │              │         │         │         │    ├─文明_庆幸 科技 文明_庆幸 科技_  庆幸 科技_庆幸\n     │         │         │         │    │         │         │              │         │         │         │    │    ├─■──庆幸 科技 文明_庆幸 科技_  庆幸 科技_庆幸_  庆幸 ── Topic: 230\n     │         │         │         │    │         │         │              │         │         │         │    │    └─■──  文明_文明_文明 意义_  文明 意义_文明 意义   ── Topic: 229\n     │         │         │         │    │         │         │              │         │         │         │    └─遥遥领先   遥遥领先_  遥遥领先  _  遥遥领先_科技  _遥遥领先  \n     │         │         │         │    │         │         │              │         │         │         │         ├─科技  _  技术_  科技_科技_核心 科技\n     │         │         │         │    │         │         │              │         │         │         │         │    ├─■──初期 阶段_这才 急  _1300hhhhhh_  起始 1300hhhhhh_1300hhhhhh   滑铁卢 ── Topic: 293\n     │         │         │         │    │         │         │              │         │         │         │         │    └─■──科技  _  技术_  科技_科技_核心 科技   ── Topic: 23\n     │         │         │         │    │         │         │              │         │         │         │         └─遥遥领先   遥遥领先_  遥遥领先  _  遥遥领先_遥遥领先  _遥遥领先 遥遥领先\n     │         │         │         │    │         │         │              │         │         │         │              ├─■──遥遥领先   遥遥领先_  遥遥领先  _  遥遥领先_遥遥领先  _遥遥领先 遥遥领先 ── Topic: 18\n     │         │         │         │    │         │         │              │         │         │         │              └─■──路线   这才_路线  _  路线  _  路线_这才     ── Topic: 343\n     │         │         │         │    │         │         │              │         │         │         └─早该  _    早就_早该_  早该_  早该  \n     │         │         │         │    │         │         │              │         │         │              ├─■──说    _  早就 发现_凎 发现_早就 发现_  凎 发现 ── Topic: 298\n     │         │         │         │    │         │         │              │         │         │              └─■──早该  _  早该_  早该  _早该_昨天 ── Topic: 199\n     │         │         │         │    │         │         │              │         │         └─逼   牛_  学废_学废_  学废  _学废  \n     │         │         │         │    │         │         │              │         │              ├─逼   牛_  学废_学废_  学废  _学废  \n     │         │         │         │    │         │         │              │         │              │    ├─逼   牛_  牛  _  牛 逼_牛  _苹果\n     │         │         │         │    │         │         │              │         │              │    │    ├─无敌  _无敌_  无敌  _  无敌_无敌   无敌\n     │         │         │         │    │         │         │              │         │              │    │    │    ├─无敌  _无敌_  无敌_  无敌  _无敌   无敌\n     │         │         │         │    │         │         │              │         │              │    │    │    │    ├─r1_  原理_  r1_r1  _  r1  \n     │         │         │         │    │         │         │              │         │              │    │    │    │    │    ├─■──r1_r1  _  r1_  r1  _  原理 ── Topic: 289\n     │         │         │         │    │         │         │              │         │              │    │    │    │    │    └─■──  基础_人才 想_基础 人才 想_想   基础_  基础 人才 ── Topic: 192\n     │         │         │         │    │         │         │              │         │              │    │    │    │    └─  无敌  _  无敌_无敌  _无敌_无敌   无敌\n     │         │         │         │    │         │         │              │         │              │    │    │    │         ├─  无敌_  无敌  _无敌  _无敌   无敌_无敌\n     │         │         │         │    │         │         │              │         │              │    │    │    │         │    ├─■──性格  _性格_不太_  gpt_gpt   gpt ── Topic: 81\n     │         │         │         │    │         │         │              │         │              │    │    │    │         │    └─  无敌  _  无敌_无敌   无敌_无敌  _无敌\n     │         │         │         │    │         │         │              │         │              │    │    │    │         │         ├─■──  无敌_  无敌  _无敌   无敌_无敌  _无敌 ── Topic: 148\n     │         │         │         │    │         │         │              │         │              │    │    │    │         │     

In [20]:
hierarchical_topics = topic_model.hierarchical_topics(docs)
hierarchy = topic_model.visualize_hierarchy(hierarchical_topics=hierarchical_topics, width=1200) # custom_labels=topic_labels_dict
hierarchy.write_html('hierarchy.html')

100%|██████████| 343/343 [00:00<00:00, 477.49it/s]

In [21]:
heatmap = topic_model.visualize_heatmap(n_clusters=3, width=1200) # custom_labels=topic_labels_dict
heatmap.write_html('heatmap.html')

Visualisation du classement de tous les termes sur tous les sujets. Chaque sujet est représenté par un ensemble de mots. Cependant, ces mots ne représentent pas tous le sujet de manière égale. Cette visualisation montre combien de mots sont nécessaires pour représenter un sujet et à partir de quel seuil l'effet bénéfique de l'ajout de mots commence à diminuer.

Il ya deux axes :
- x : Représente le rang des termes dans chaque sujet. Le terme avec le score c-TF-IDF le plus élevé a un rang de 1, le deuxième terme a un rang de 2, et ainsi de suite.
- y : Montre le score c-TF-IDF des termes. Plus le score est élevé, plus le terme est représentatif du sujet.

In [22]:
topic_model.visualize_term_rank(log_scale=True).write_html("term_rank.html")

In [23]:
topic_model.visualize_topics().write_html("visualize_topics.html")

Enregistrer les résultats dans un csv

In [24]:
PREDICTIONS_FILE = 'bertopic_topics_notebook.csv'

results = topic_model.get_document_info(docs=docs)
# results.to_csv()

# Latent Semantic Analysis (LSA)

LSA commence par créer une matrice terme-document. Les valeurs de la matrice sont généralement des scores TF-IDF qui pondèrent l'importance des mots dans chaque document. La matrice est ensuite décomposée en trois matrices à l'aide de la SVD. Ces matrices capturent les relations entre les termes et les documents. Enfin, en sélectionnant uniquement les premières composantes singulières, LSA réduit la dimensionalité tout en conservant les informations les plus importantes, ce qui permet de découvrir les sujets sous-jacents.

```python
embedding_model = sklearn.pipeline.make_pipeline(
    sklearn.feature_extraction.text.CountVectorizer(analyzer="word", tokenizer=lambda x: x.split(" ")),
    sklearn.decomposition.TruncatedSVD(10)
)
```

=> https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html#sklearn.decomposition.TruncatedSVD

In [26]:
def set_model_parameters_lsa():

    # Step 1 - extraction des embeddings
    embedding_model = sklearn.pipeline.make_pipeline(
        sklearn.feature_extraction.text.CountVectorizer(analyzer="word", tokenizer=tokenize_zh),
        sklearn.decomposition.TruncatedSVD(n_components=15)
    )

    # Step 2 - réduction des dimensionalité
    umap_model = UMAP(angular_rp_forest=True, metric='cosine', n_components=10, n_neighbors=20, min_dist=0.1)

    # Step 3 - Cluster reduced embeddings
    hdbscan_model = HDBSCAN(min_cluster_size=10, min_samples=5, prediction_data=True, metric='euclidean', cluster_selection_method='eom')
    # hdbscan_model = KMeans(n_clusters=50)
    # hdbscan_model = sklearn.cluster.AgglomerativeClustering(n_clusters=50)

    # Step 4 - Tokenisation des topics
    stoplist = list(STOP_WORDS)
    # ADDITIONAL_STOPWORDS = ["qu", "ya", "faut", "euh"]
    # stoplist.extend(ADDITIONAL_STOPWORDS)

    vectorizer_model = CountVectorizer(stop_words=stoplist, ngram_range=(1, 2))

    # Step 5 - Création de la représentation des topics
    ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True, bm25_weighting=True)

    # Topic model
    return BERTopic(
        embedding_model=embedding_model,
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        vectorizer_model=vectorizer_model,
        ctfidf_model=ctfidf_model,
        language='chinese',
        n_gram_range=(1,2),
    )

In [27]:
topic_model = set_model_parameters_lsa()

In [28]:
topic_model.fit(docs)

In [29]:
topic_model.generate_topic_labels(nr_words=20, topic_prefix=True, word_length=None, separator='  --  ')

['-1  --  凑合  --  magi  --  magi magi  --  新效转换改做超越本质  --  凑合 凑合  --  穿越者  --  穿越者 穿越者  --  巧手先生  --  太牛了  --  很好',
 '0  --  生快 生快  --  协同 协同  --  协同  --  metaxr metaxr  --  生快  --  抢票 抢票  --  metaxr  --  抢票  --  牛蛙 牛蛙  --  八两半斤',
 '1  --  公平  --  公平 公平  --  底特律 变人  --  愚者抬杠  --  人工  --  别这样  --  4万人民币  --  罗老师  --  罗老师 别这样  --  extermination',
 '2  --  坐云上  --  假新闻  --  what  --  宇智波家族  --  清明节蹦迪  --  管泽元 se4  --  宇智波家族 管泽元  --  小白鼠  --  眼瞎  --  眯眯眼 what',
 '3  --  ai助手  --  ai助手 ai助手  --  ai就是未来  --  ai工具  --  反人类组织用ai搞破坏怎办 ai预测彩票呢  --  战斗力只有5 ai春晚  --  战斗力只有5  --  就是ai声线  --  怎么不选ai男士 悄悄投入一批ai人到社会中  --  悄悄投入一批ai人到社会中 什么时候开始卖ai伴侣',
 '4  --  太正确了  --  形象还是一个黑人 太正确了  --  形象还是一个黑人  --  没有啊  --  落后太多了  --  有些畸变 但是太牛了  --  机翻成纳米了 物竞天择  --  水流向反了 人在飘  --  机械飞升 又又在大吹特吹了  --  0差不多',
 '5  --  夺少  --  科幻  --  还有高手  --  纳米级  --  没有本质不同  --  等会儿可持续  --  纯记忆功能  --  算了吧 艾达  --  科幻 一帆翻译  --  红队 啥意思',
 '6  --  五彩斑斓的黑  --  五彩斑斓的黑 五彩斑斓的黑  --  强者的发型  --  四条腿各走各的  --  智慧的眼神  --  矫健的步伐 集体摸鱼的厨师  --  矫健的步伐  --  瞎扯的 符合逻辑的马  --  20w的显卡  --  独有的害羞 抄小米的',
 '7  --  机飞  --  机飞 机飞  --  好棒  --  垃圾统统宰掉狗警  --  rua  --  不要回答  --  飞升  --  疑犯追踪  --  源神  --  电子榨菜更新啦',
 '8  --  怕不是用中国数据训练的吧 大势所趋  --  柯南带过  --  果子在国内也只能用文心一言 openai形同虚设的宣言  --  注意看 被子移动导致的气体把被子顶起一个小包  --  注意右下角 openai的标志  --  注意右下角  --  注定不会普及 糊的很  --  注定不会普及  --  没踩实地面的 请注意  --  没踩实地面的',
 '9  --  不支持  --  运行不等于训练  --  通一千问  --  0仍不自带联网搜索功能  --  细嗦不合适 不信  --  用来打骚扰电话简直分不出来 按道理机器人没有自我意识  --  甚至不需要人类 模型分推理和不推理真的多此一举  --  碰撞不对  --  用来打骚扰电话简直分不出来  --  碰撞不对 边缘就像抠图不合格',
 '10  --  对面怎么看到本人啊那这样  --  贾维斯啊 讲半天没讲多少tops啊  --  已经迭代很多代了兄弟们  --  炸裂 英伟达也来  --  华为也可以啊 炸裂  --  华为也可以啊  --  你们惊讶什么 华为也可以啊  --  你们惊讶什么  --  真开源啊  --  真开源啊 你们惊讶什么',
 '11  --  closeai  --  closeai closeai  --  我准备好了  --  笑死我了  --  我更倾向于大部分人类都要下地府了 我可以开始抄袭了  --  我靠竟然都这么厉害了  --  我看太牛壁了  --  我甚至情不自禁在屏幕前鼓掌了 我想到了  --  我说实话初版真的已经可以应付简单场景应用了  --  看到西夏文我暂时放心了 我说实话初版真的已经可以应付简单场景应用了',
 '12  --  给你拜个年  --  给你拜个年 给你拜个年  --  底盘太低  --  信你个鬼  --  六指琴魔  --  genie太美  --  矩阵 遥遥你马  --  期待鸡你太美  --  有后门的说控制你就控制你 然后弹出  --  底盘太低 底盘太低',
 '13  --  卧槽卧槽卧槽 卧槽  --  卧槽卧槽卧槽  --  卧槽 卧槽卧槽卧槽  --  卧槽不得了 卧槽  --  一句卧槽  --  呵呵卧槽  --  卧槽阿凡达 卧槽  --  卧槽阿凡达  --  卧槽好帅 卧槽  --  卧槽好帅',
 '14  --  美味  --  24节气  --  编码 一次性  --  黄色  --  混沌之子 智绘神州  --  整体规划 丹青创天  --  智绘神州  --  文心一言即将迎来重大更新 her  --  智械危机 蜕变  --  泰裤辣 吹嘘',
 '15  --  天网 遥遥领先  --  刀剑神域  --  遥遥领先 天网  --  遥遥领先 遥遥领先  --  遥遥领先已成为贬义词  --  遥遥领先 人工智障  --  马上遥遥领先  --  皆若空游无所依  --  遥遥领先已成为贬义词 数字生命要来啦  --  人工智障',
 '16  --  o1  --  注意看右边的水浪 光线追踪必不可少的水和倒影  --  情绪真的比现在的版本充沛 他弄给出固定的反应和数据库调取的  --  总能把名字翻译的很俗 没有隐私的时代到来啦  --  情绪真的比现在的版本充沛  --  未来20年无敌的存在  --  我要谷歌去年的栏目大模型 真是推动人类进步的人  --  我们的公司呢 因为老黄只穿一个季节的衣服  --  我要谷歌去年的栏目大模型  --  最缺德的一集 效果绝对不如最差的4k电视',
 '17  --  天网来了  --  来了 来了  --  来了 机器人积点到了  --  看到了  --  来了 左上角刷了个人  --  霍金死早了  --  来了 机器战警来了  --  来了 法学硕士笑不活了  --  来了 看到了  --  来了 看成gta5了',
 '18  --  3000刀还能吊打macmini  --  能不能造梦 啥时候能识别温州话  --  炒糖色和勾芡能比咖啡拉花还难  --  我靠 人类进化不带上我系列  --  手柄  --  所以和老马有什么关系 做不到完美就等于白费  --  所以都活不过40  --  没看过发布会 什么主持人  --  我们在干嘛  --  没网 你还想把gpt整个塞进眼镜里',
 '19  --  我不信  --  有人带节奏 这个我估计普通显卡带不动  --  电脑起码15分钟  --  活在哪里 到哪里去  --  比如我在火星  --  理发师 这也能卷到我  --  每个国家都需要  --  电脑起码15分钟 音频我还没怎么玩  --  真敢啊  --  真敢啊 siri',
 '20  --  这么快  --  自己出去  --  最强又易主了  --  放调料时适量它懂吗  --  搞人体湿件 与什么合作  --  现在呢  --  放调料时适量它懂吗 竟然还会让杯底放在抹布上  --  机器人维修呢  --  最强又易主了 70b  --  然后开枪射击',
 '21  --  6批 救命  --  6批  --  救命  --    --    --    --    --    --    --  ',
 '22  --  完辣  --  华为二十年前就有了  --  把充分必要条件理解明白就成了 穿戴设备就无敌了梦境电影  --  然后大黄就被公司开除了 dog  --  断网就尴尬了 然后语言就退化了  --  更新多了不敢想  --  然后大黄就被公司开除了  --  明年国内就普及了  --  然后语言就退化了  --  断网就尴尬了',
 '23  --  牛逼 牛逼  --  华为牛逼  --  牛逼 华为牛逼  --  6逼  --  牛逼牛逼牛逼 牛逼  --  意大利牛逼  --  牛逼 真牛逼  --  这儿场景太牛逼 牛逼  --  牛逼 老马牛逼  --  牛逼 这儿场景太牛逼',
 '24  --  不让人的创造力就真的被扼杀了  --  好事  --  好事 不让人的创造力就真的被扼杀了  --  50次很少了好么  --  本来要昨天播的 结果被嘎了  --  灯deepseek出r99的时候gpt  --  注意看那个人的手表 一个转场就没了  --  没有畸变了  --  淘宝十几块的智能模块也可以 张口就来  --  没有控制媒体的选项',
 '25  --  我的天  --  up你的声音好像和我对话得gpt啊  --  面试不用辅助的自信就是我的竞争力  --  我的还可以支持方言呢 我真想描述一下自己做的一些奇怪的梦  --  我看这个拜登就像假的  --  我的评价 没有代差  --  我看到一个快出生的婴儿  --  我真想描述一下自己做的一些奇怪的梦 up你的声音好像和我对话得gpt啊  --  我的还可以支持方言呢  --  我真的需要一个可以帮我收拾屋子的机器人',
 '26  --  5555  --  是被会用ai的人淘汰的 说好的先限制ai呢  --  然而这个节目里所有的视频都不是ai做的 全都是人工特效  --  然而他是用虚幻引擎做的 和ai关系也不大  --  现在ai生成视频这么厉害 不知道都会觉得是ai生成的视频  --  然而这个节目里所有的视频都不是ai做的  --  现在说话的也是ai 我终于能知道片儿的剧情是什么了  --  现在ai生成视频这么厉害  --  然后ai合成 想办公司但想一个人单干  --  现在说话的也是ai',
 '27  --  苹果xr  --  苹果xr 苹果xr  --  5就能做了  --  这个太炸裂了 这个已经很真了  --  这个太老了 这个交互其实就不如copilot了  --  这个小镇也太真实了  --  这个太离谱了 这个嘴绷不住了  --  这个太酷了 这个有点牛了  --  这个太真了 这个毛发太糙了  --  这个太老了',
 '28  --  天空是绵绵的糖  --  google首席架构师是他的学生  --  是的哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈  --  程序员是最开心的  --  除非是故意的doge  --  程序员应该是最不用担心的  --  是挺欢乐谷的  --  科学的尽头是神学  --  确实是苹果的风格 死的是包图网  --  确实是苹果的风格',
 '29  --  赞美欧姆弥赛亚  --  赞美欧姆弥赛亚 赞美欧姆弥赛亚  --  搜魂  --  搜魂 搜魂  --  才3亿 不止吧  --  必须是我水强哥 识别背景是木制  --  怕锤子  --  怕锤子 加速  --  0出来才多久  --  没网证网号怎么监管 不够遥遥领先',
 '30  --  就离谱  --  ame波高  --  最后就像烧石头 马斯克自己就在赛道上  --  法律知识库谁装谁就不想玩  --  想象就能出视频  --  没输出符号表达式就没什么意义  --  水人就得波高 ame波高  --  水人就得波高  --  来个鱼香肉丝就得崩 明天就原创  --  来个鱼香肉丝就得崩',
 '31  --  ai保安都已经烂大街了  --  就这么炸裂了  --  美国刚开会禁止了ai按按钮  --  外挂领域已经有ai外挂了  --  真的能用ai算命了 苹果再不发展ai就要落后时代了  --  量子计算机到时候跟ai一结合就爽了  --  疯了ai绝对要出事 ai文旅整活了  --  疯了ai绝对要出事  --  画小二 算命  --  画小二',
 '32  --  这个厉害  --  做梦梦到过这个  --  这个手是真不行  --  这个远近层次感 这个算不算穿模  --  这个眉眼看着像韩裔  --  马赛克这个世纪难题  --  这个手哈哈 这个不行  --  这个特效好烂 这个手仍然画不好  --  这个特效好烂  --  这个火比较呆 这个最真实舒服',
 '33  --  2024年6月  --  绿皮在20k就要出现了 我成化石了  --  文心什么时候追上gpt4了 又来  --  模仿者闹麻了  --  是机器人更智能化了  --  正确什么时候变成贬义词了  --  旁白声音换了  --  正确什么时候变成贬义词了 动一动就没有了版权  --  文心什么时候追上gpt4了  --  揭密了什么 以后可以对话了',
 '34  --  200刀的受众是打算面向谁啊  --  眼镜是虚拟的  --  是仿冒品  --  有隔离  --  既然是预测  --  本文也是chatgpt4朗读的  --  眼镜是虚拟的 看着挺别扭  --  核弹出现的时候大家也是这么害怕的  --  核弹出现的时候大家也是这么害怕的 说到底都是工具而已  --  此消息更多的是噱头',
 '35  --  战5渣  --  地平线5 5脚  --  地平线5  --  5脚 战5渣  --  5脚  --    --    --    --    --  ',
 '36  --  过拟合  --  手臂肌肉那感觉怪怪的  --  真牛逼想拥有 openai  --  黑人在打篮球呢  --  模型师失业在即 与此同时美军在干什么呢  --  苹果还在憋大招 未来看谁脑补能力强  --  苹果还在憋大招  --  脚在滑动 神奇动物在哪里  --  脚在滑动  --  脚在滑 要慶幸現在還能夠分辨',
 '37  --  文言一心  --  文言一心 文言一心  --  只需要你给钱  --  微软ceo 不需要你有脑子  --  国内不报道你只能自己去找 科技可以给工作和生活带来便利  --  只需要你给钱 文言一心  --  国内不报道你只能自己去找  --  当然想睡觉  --  如果你只会做ppt那活该失业 这牛阿  --  大黄觉得你在把它当小丑 苹果能锤子',
 '38  --  前面发言不如老鼠  --  65岁能体面的退休  --  用的西方字母拼音 还是外国人发明的  --  迟早会成为  --  毕竟完全不可控的东西  --  碳基生命的意义在于创造硅机生命  --  没事 反正我们的茅台科技会出手的  --  没有量子那么深层的东西  --  没有量子那么深层的东西 这不是cove的声音嘛  --  然后明年继续被al的进化打脸',
 '39  --  这把父子局  --  这光影  --  氪金狗眼  --  3050笔记本行不行  --  这招牌一眼东京  --  这还要结婚生孩子干嘛  --  这眼睛  --  这把父子局 这把父子局  --  这玩意非常先进 这把父子局  --  这玩意非常先进',
 '40  --  不怕我们有飞天茅台  --  有嗨用 我们有飞天茅台  --  这块有问题 有这么个监控者意味着彻底失去隐私  --  注意中间窗户有缩进 文字还是有问题hhh  --  鞋底有打滑  --  没事我们有华为 有图有真相时代彻底告破  --  有嗨用  --  此境只当梦中有 弹幕里有数字生命提前预知未来  --  此境只当梦中有  --  果真有七匹 狗有这么灵光',
 '41  --  好强啊  --  厉害啊  --  6啊  --  2w刀啊只要  --  真抽象啊  --  速度挺快啊  --  还有根线啊  --  这是说到做到啊  --  还有根线啊 妙啊  --  移轴镜头啊 西部世界真的存在啊',
 '42  --  能用吗  --  b站独家直播吗  --  汪汪队  --  这是英国人吗 国内不是人均吊打吗  --  道德屏障不是扣分点吗  --  能用吗 送外卖吗  --  比得过脚本吗  --  黑客帝国吗  --  能生孩子吗  --  能活到240岁吗 无监督学习不会出事吗',
 '43  --  emmm岛国电影  --  建议重温电影her  --  说白了就是色图 电影重组开启  --  训练素材本来就是3d模型 盘古就是答辩  --  越来越像假人  --  眼睛里面就是一个万千世界小宇宙  --  左脚踩右脚上天  --  骗子  --  电影重组开启 照方案输入命令和微调还不是需要程序员  --  电影重组开启',
 '44  --  贾维斯  --  349都可以买两台电脑了  --  开头都说姓陈了还韩裔 都来分蛋糕了  --  都要rap起来了  --  都来分蛋糕了  --  都泄露了关闭有b用  --  都来分蛋糕了 设计和前端都不用干了  --  设计和前端都不用干了 贾维斯  --  鸽子都学秃了  --  开头都说姓陈了还韩裔',
 '45  --  10刀月  --  明显不如4好吗 离谱  --  疯狂买流量  --  现在只需要原画师就行 什么原画师早被取代了  --  然后意识数据化  --  生产力会比现在高几个几十个量级 前端失业  --  没有出幻觉  --  疯狂买流量 闹麻了  --  疯狂证明sora技术漏洞  --  疯狂证明sora技术漏洞 鸡蛋里硬找骨头而不是惊讶openai没对手了',
 '46  --  ai一周发生的事是实业企业的一年的事  --  原来奇异年改变世界的是ai  --  这配音也是ai的吧 言外之意是在反ai布道就是跟不上时代的老人是吧  --  视频语音也是ai生成的吧 ai代替人类是早晚的事  --  音乐也是ai生成的吗  --  视频语音也是ai合成的吧 准确讲是人类和跪舔ai的人类必有一战  --  化的 ai是可以生成剧情的  --  第一批跟高级智能ai工作的是推特员工 视频语音也是ai合成的吧  --  第一批跟高级智能ai工作的是推特员工  --  程序员是唯一可以物理嫁接头发到ai的',
 '47  --  来啦 来啦  --  1050ti看完当场升天  --  马上要成为现实  --  游戏要做到这样才行  --  谷歌要放大招  --  要adobe  --  要一个厚厚的薄片  --  要adobe 搞錯方向要完  --  直接快进到  --  大家一定要关注鹿野灸 简迷妮要力天',
 '48  --  用上了  --  1怎么会这么快  --  看到标题人傻了  --  这样是不是能diy电影了  --  走着走着人没了哈哈  --  踩死人了  --  走着走着人没了哈哈 人走着走着没了  --  能不能把墙拆了  --  我们还在训练跳科目三了 做mv和广告动画不用外包了  --  老了就靠它了',
 '49  --  太假  --  太假 太假  --  无敌  --  恐怖谷  --  恐怖谷 恐怖谷  --  太美  --  难绷  --  这手难绷 无敌  --  难绷 太美  --  这是生产队不要驴了啊 英伟达恐怖如斯',
 '50  --  学废了 学废了  --  学废了  --    --    --    --    --    --    --    --  ',
 '51  --  你说的对  --  agi必然到来  --  某些人风凉话说的飞起  --  我用的就是topaz 也是局限性很大的  --  我说的是工作流程 我用的就是topaz  --  我用的就是topaz  --  是有计划的产物 llya的人品我还是相信的  --  工作只是延缓空洞的到来  --  真好奇他是怎么工作的 后面的海水是怎么渲染出来的  --  是这样的 欧美的研发是中国的20倍',
 '52  --  5年  --  能发展出自动帮我生成游戏吗 doge  --  黑少行  --  能有啥大事  --  用n卡 还想要主权  --  直接脑里构造变成电视剧  --  直接脑里构造变成电视剧 假如我脑供血不足呢  --  知不知道注水论文不等于质量  --  知不知道注水论文不等于质量 sora  --  神经元',
 '53  --  感谢马斯克开源  --  支持开源  --  千万别开源  --  感谢阿梓开源 感谢柯南开源  --  等一波开源怪  --  感谢雷军开源 感谢华为开源  --  支持开源 我先感谢马开源  --  欢迎前来开源 感谢秦始皇开源  --  欢迎前来开源  --  感谢马圣开源',
 '54  --  普通人等着被淘汰吧 毀滅吧  --  来个动画片吧 去换华为吧  --  阿三爬吧  --  脑后插管吧 这是实拍剪辑吧  --  阿三是吧  --  这是实拍剪辑吧  --  那把东西换个位置还是不行吧  --  这是实拍剪辑吧 这是个人妖吧  --  讓sydney回來吧 阿三是吧  --  鬼扯吧',
 '55  --  ai不严谨啊  --  文科生不要乱说 ai最近爆发性发展三年  --  它就是想让你能听出来 笨蛋  --  只是ai赶巧在这时候出现  --  可以一战  --  只有人类通过ai作为工具控制人类  --  只有人类通过ai作为工具控制人类 再另外  --  好好好 这个配音就是ai  --  别说七年  --  无尽模式',
 '56  --  hhhhh  --  就是说美国载人登月造假的ai么  --  卧槽这是ai擅长的类型  --  想想一年前的ai还是巨石强森吃石头  --  芯片和ai就是新时代的国家安全核武器 卧槽这是ai擅长的类型  --  竟敢假定ai的性别 ai就是元宇宙的基石  --  还是需要现有的视频和图片拿去喂ai啊  --  无解宇宙中的ai之神 已有的视频上进行ai重绘  --  选美比赛  --  扼住ai 的咽喉',
 '57  --  我超 我超  --  遥遥领先 我们遥遥领先  --  我们遥遥领先  --  我们遥遥领先 遥遥领先  --  教育  --  缺点  --  启动  --  我超  --  我超 信息时代生产力飞升  --  我们还在研究敬酒 他们已经',
 '58  --  5一直都比4快  --  机器人没有办法帮老板背锅  --  天天净吹牛不干活 盲人怎么看见  --  多模态 只能说和竞品不在一个level上  --  天天净吹牛不干活  --  我们会不忘初心  --  如果哇为先出 海狗不又吠腾  --  天天造神 只要涉及到印度人就不可靠  --  如果哇为先出  --  我们不需要',
 '59  --  太恐怖了  --  太离谱了  --  太厉害了  --  太抽象了  --  炼丹哈哈哈哈哈哈哈哈哈太形象了  --  绷不住了哈哈哈哈哈哈哈  --  炼丹哈哈哈哈哈哈哈哈哈太形象了 苹果真的太强了  --  苹果真的太强了  --  苹果真的太强了 细节丢失太严重了  --  语调太无敌了',
 '60  --  和平和平和平  --  防御性 250颗核弹  --  防御性  --  国际稳定  --  国际稳定 绝对不首先使用核导弹  --  绝对不首先使用核导弹  --  军部不使用任何新范式任何新概念改做一切产物全方位本质 你们相信吗  --  军部不使用任何新范式任何新概念改做一切产物全方位本质  --  绝对不首先使用核导弹 军部不使用任何新范式任何新概念改做一切产物全方位本质  --  和平性',
 '61  --  40生成的吗  --  负反馈  --  画面那全是闪烁的  --  机制 容忍  --  画面那全是闪烁的 算法不一样  --  普通人是没有脑子的npc吗 这是最简单的人机交互啊  --  普通人是没有脑子的npc吗  --  是祝你们一切皆好吧 这怎么听出来是印度口音的  --  是祝你们一切皆好吧  --  是什么意思 画饼的是吧',
 '62  --  atm机后面其实蹲了个人是吧  --  核污染变异了这是真的  --  这逼格是真的太高了 欢乐谷  --  闭源不进步了是吧 听着以为是卡带了呢  --  闭源不进步了是吧  --  翻译类工作是基本不需要人来做了 希望是尽量多挤了一点  --  这回是完全被微软偷家了  --  这是下血本了 上面绑着个笔记本属实是绷不住了  --  这是下血本了  --  赛博情侣可以看得见了是吧',
 '63  --  不事先告诉你  --  什么特色地区 什么冰雹猜想  --  还老一辈 不事先告诉你  --  还老一辈  --  什么赛博行为 什么时候才能写某类小说  --  男友什么时候来 什么赛博行为  --  要什么感情 男友什么时候来  --  要什么感情  --  什么黑客帝国  --  还要什么相亲',
 '64  --  heygen  --  快递公司  --  首先应用于间谍和军事活动  --  未来必然会和穿戴设备甚至脑机结合 禁止中国人使用  --  除了中国  --  蕉迟但到  --  计算能力和数据信息  --  蕉迟但到 华为  --  欢迎把你们公司商业数据交给我们 快进到智械危机和守望先锋诞生  --  鲸和鱼不分',
 '65  --  7年前的实验  --  拿实拍的来骗兄弟 不是为什么他的灵巧手这么强  --  看不起遥遥领先的酱香科技 相当于不断把输入压缩进定长的prompt里  --  那个很nb的  --  这有病的文案  --  这算力怎么跃进的  --  这有病的文案 大鹅够干啥的  --  真的假的 昭和的曼  --  手指脚趾的个数还是不行呢 另一种的图生图模式  --  门外竖着去吧',
 '66  --  小脑很发达 小脑很发达  --  小脑很发达  --  claude中文能力很不错  --  看起来真的很激动  --  奥特之父  --  其实还好  --  其实还好 非常不错  --  擦杯底这下很到位  --  非常不错 小脑很发达  --  非常不错',
 '67  --  有点意思  --  有点可爱  --  有点意思 日本有点抽象  --  角色模型还不是很好 鸡肋功能  --  第三个没用过  --  眨眼看着有点怪  --  身高有点奇怪  --  身高有点奇怪 手臂肌肉有点奇怪  --  阶段4有点扯淡  --  阶段4有点扯淡 有点意思',
 '68  --  力大砖飞  --  往后飞好评 好主意  --  猫猫也可以啊  --  讯飞星火挺不错 好耶  --  往后飞好评  --  这不比5毛特效好 往后飞好评  --  这个光影真的赞  --  这个光影真的赞 ai光追  --  这个好 真遥遥领先  --  这个妙啊',
 '69  --  rtx on  --  rtx  --  on  --  阿弥陀佛  --  阿弥陀佛 阿弥陀佛  --  let any  --  any outstanding  --  much  --  military  --  military department',
 '70  --  barett的手在狂抖  --  比较抽象的画面还是做不好  --  这里音频用的suno 爆论  --  那天生盲人的思维图像什么样子的呢 没一个能用的  --  那天生盲人的思维图像什么样子的呢  --  老中的项目一如既往让人发笑 高40  --  这样的饺子没灵魂  --  这里在高度差大的雪上走 我要给春日野穹一个完整的生命  --  这里在高度差大的雪上走  --  能分清不同的谈话对象',
 '71  --  底特律 大变活人  --  你好  --  大变活人  --  底特律  --  翻译  --  快来买卡 翻译  --  黑客帝国奶牛版  --  底特律 化人  --  快来买卡  --  汪汪历险记',
 '72  --  心灵安抚师  --  ai ai  --  光追皮衣  --  接ai ai人情世故真的比人厉害  --  其实就是ai p图吧  --  去查查呗  --  好多ai up在播  --  刻板印象在硅基生物里完美复刻  --  实时ai游戏世界  --  其实就是ai',
 '73  --  恭喜  --  李姐万岁 男人  --  老有所养  --  老有所养 舵机  --  见切 口阝可囗牙  --  舵机  --  貓貓 amazing  --  见切  --  神迹 求和  --  貓貓',
 '74  --  同传  --  温迪 这我还写集贸啊  --  陷太少  --  这我还写集贸啊 同传  --  这图 加强雷军  --  这要是拿去做诈骗我都不敢想能挣几个w 还不如看电脑屏幕舒服  --  这图  --  陷太少 未来进行处决  --  难听  --  难听 小进步',
 '75  --  2026年在做什么梦呢  --  看着办 是好事  --  炒概念都是好手  --  我们死了以后几百年都没机会出现 人家说了  --  我谢谢 猎户集团明牌了这是要  --  我理解是类似于人类大脑 可能记住了  --  我谢谢  --  是能跑 能推理  --  开源了再看是吧 是华裔啊  --  有博主被邀请体验了 确实是个新篇章',
 '76  --  aloha读音没错吧  --  真讲究 甲骨文是一个数据库公司  --  更加消费社会  --  更卷是真的  --  滥用的话又是五色令人目盲 更加消费社会  --  牛逼 这才是正解  --  是追不上了 国外是真智能  --  是追不上了  --  是美国版可灵sora bgm是美剧西部世界  --  是美国版可灵sora',
 '77  --  5了  --  已经可以出电影了 以后可以自制宝莱坞大片了  --  真有希望可以看见家政机器人了 终于可以自主研发了哈哈  --  终于可以自主研发了哈哈  --  真有希望可以看见家政机器人了  --  英语科目可以压缩到50分了  --  英语科目可以压缩到50分了 终于可以不用学外语了  --  这下它们可以进化了  --  这下它们可以进化了 可以和宠物同声传译了  --  这下餐饮行业可以大规模裁员了',
 '78  --  完了完了  --  好了  --  效率提升了  --  完了 它们能动手了  --  完了完了 ai要统治地球了  --  岗位就少了 太大了  --  完了 绝望了  --  已经了解符号了  --  它们能动手了 效率提升了  --  它们能动手了',
 '79  --  我想吃  --  测谎仪 测下我老公  --  我是不是真实存在的人 如果不是告诉我说是ai生成  --  我现学  --  我都察觉不了  --  我是谁  --  我需要这个狗叫翻译  --  我是不是真实存在的人  --  我擦 这视频最后一句吓我一跳  --  我想吃 少拿实拍视频来骗我',
 '80  --  10人50亿  --  怪不得之前一堆人逼他辞职 試毒機器人  --  谜语人哈哈 这一下扭头跟人一样  --  真丶听不懂人话  --  河北保定人  --  还是人便宜  --  还是人便宜 丹麦人  --  这一下扭头跟人一样  --  这一下扭头跟人一样 跟人一样  --  这不比仿生人有用',
 '81  --  图灵测试  --  ai一键就它好了  --  有个电影就是ai接管 结果人类天天玩  --  工业ai相比通用ai太简单了  --  它们到底花了多少心思训练ai 是时候训练一下人类啦  --  完啦 这下没办法开发ai了  --  是时候训练一下人类啦  --  影视广告行业怎么办  --  弹幕有点吹过了  --  弹幕有点吹过了 ai还是要看我们这边',
 '82  --  所以ai春晚是必然 ai开发游戏  --  才发现是ai配音 老人z  --  那要是没看到坏人请问是抓ai吗  --  未来一定是ai配合vr生成元宇宙 一看文字就知道是ai  --  配音也是ai  --  配音也是ai ai真的是未来啊  --  配音都是ai  --  配音都是ai 文案估计也是ai  --  镜面反射错误  --  镜面反射错误 救命怎么连这条视频都是ai语音生成',
 '83  --  4的cove声线  --  这个是heygen的开源平替 这个是可以实现的吗  --  这个解说语音甚至是openal的2333  --  这个视频也是gpt配音的 但是这个造物未必指的是人类  --  这个语音好像是gpt4的  --  这个语音好像是gpt4的 这个才是最牛的  --  这个都是相关联的  --  这个都是相关联的 这个是heygen的开源平替  --  这个配音是gpt的声音好像  --  这个配音是gpt的声音好像 这个二才是最重要的',
 '84  --  牛的  --  闪电有点三毛钱特效的感觉 怎么有种山寨电影的感觉  --  这表看来其它的里面还是可灵最能打 笑的青筋蹦起  --  还是有点假的 这是openai的语音  --  老美引领科技还是很强的  --  还是一致性的问题  --  笑的青筋蹦起  --  还是有点假的  --  电视机的雪花有点离谱 文字还是错乱的  --  这是openai的语音',
 '85  --  1chat  --  目前来说 根本不用担心事业问题  --  接管就接管吧  --  才能更快更好的研发 30亿不会的  --  无论是gpt的智能  --  强化压剪信息冗余  --  真正的在家体验西部大冤种  --  无语 哇喔  --  日本办公太繁琐  --  日本办公太繁琐 年轻人又少',
 '86  --  2023年是变形金刚元年  --  如果把脑电波能转变成视频 国内又用不了  --  被打残 siri  --  能生成稳定高清360度物体也就代表文生3d马上出现 人类即将进入虚拟世界  --  说实话硕博问题真的能提供帮助的话200刀真不贵  --  然后ai自己创造躯体  --  还没说到  --  如果把脑电波能转变成视频  --  每天节省5分钟  --  日本缺劳动力 第二日本终身雇佣制',
 '87  --  只有你这种毫无基础的人才会这么想  --  投票  --  之前的炒菜机器人你确定不是锅加点配件吗  --  脑接口  --  这你动效不还是ae做的吗  --  赛尔号 参会人员会扫描你的脸构建虚拟人物  --  脑接口 你的记忆没有隐私  --  这个旁白就很符合你的视频 之前的炒菜机器人你确定不是锅加点配件吗  --  能问出你这种问题的人类确实比较适合灭绝 文明  --  这你动效不还是ae做的吗 这个旁白就很符合你的视频',
 '88  --  能炒股嘛  --  能炒股嘛 能炒股嘛  --  avp能带上飞机么  --  立帖为证2024直接跳2077  --  能不能吃面呢 看人物动态细节能看出来  --  立帖为证2024直接跳2077 人家能写出软件  --  能不能把衣服去掉 avp能带上飞机么  --  能不能吃面呢  --  能操作预制菜么  --  能不能把衣服去掉',
 '89  --  德属加纳  --  now  --  幻视  --  求量产 pixar  --  近视宝宝退出直播间 指环大陆  --  视虫为神 无端  --  误听 马丽  --  误听  --  看成皮眼子  --  19世纪',
 '90  --  顺拐了  --  三连了  --  鸟飞进自拍杆了  --  这太吊了 牛逼坏了  --  終於來了  --  这张太扎心了 鸟飞进自拍杆了  --  这太吊了  --  碉堡了  --  这张太扎心了  --  破音了 恋爱了',
 '91  --  我敲 太厉害了  --  我敲  --  我摊牌了  --  没人比我更懂 太典了hhh  --  我摊牌了 我就得痞老板  --  有工作流了 可惜blend我不会  --  有工作流了  --  我马上不想对话了 坏了  --  我马上不想对话了  --  我靠 这个厉害了',
 '92  --  这是ai  --  这是ai 这是ai  --  ai乔布斯  --  有真人何必劳烦ai呢  --  全人类ai用什么语言训练 ai就是上个滤镜  --  树莓派那配置还能跑ai 建个图都卡  --  这个音色不就是ai吗 这是ai  --  这是ai 全人类ai用什么语言训练  --  这是ai配音吗  --  这是ai配音吗 没有ai先生吗',
 '93  --  一辈子不用请保洁我可以  --  我现在还在生成龙年海报 然而我在台湾可以用  --  还好我没下手买新显卡  --  能进入我么 我挺好奇故意写错会发生什么  --  看你们怎么摸着我过河 我感觉自己在大清  --  躺平派表示我可以起来 我想去美国  --  然而我在台湾可以用 我评价个冰箱还得学会制冷么  --  还好我没下手买新显卡 我一定要活到那个时候  --  那他一定很懂我舍友  --  那他一定很懂我舍友 分镜我很需要',
 '94  --  bing bing  --  bing  --  肌肉云 bing  --  肌肉云  --  伊藤润二 bing  --  伊藤润二  --  bing 伊藤润二  --    --    --  ',
 '95  --  ai与游戏根本天然相冲  --  搜集比赛视频 ai指导运动员更好的训练  --  节目还有半小时 还有高手  --  所谓小说中的系统可以理解为超级ai 只会两个ai尬聊  --  顺便赠送一屋子的ai画  --  能学会说谎  --  美国将再次伟大 游戏爱好者的福音  --  美国将再次伟大  --  给我这边的ai点准备时间 丸辣  --  给我这边的ai点准备时间',
 '96  --  6g  --  它刚才是在模仿人类语气 googie是啥  --  远见  --  视频声音也是gpt  --  这并不冲突  --  视频声音也是gpt sora  --  真的是略低于吗  --  难道他真的是天才  --  盒子也是设备  --  它刚才是在模仿人类语气',
 '97  --  一个都没看出来  --  每个月都要续费吧  --  连皱纹都很真实  --  请欣赏小粉红弹幕 聪明几倍都不管用  --  这样学好和学坏看起来都很容易 吹吧都在吹骗投资呢  --  艾斯比 弹幕小学生  --  连个网5亿次都没问题 这样学好和学坏看起来都很容易  --  艾斯比  --  连皱纹都很真实 老黄真心话  --  那确实各种诺贝尔奖都可以发给他俩',
 '98  --  牛啊  --  好啊  --  gpt4o视频都没发啊  --  这运镜可以啊  --  这么牛呗为什么当天暴跌啊 网得好啊  --  还是用不了啊  --  这么牛逼推理个a股走势啊 好啊  --  这么牛呗为什么当天暴跌啊  --  网得好啊 显卡得多好啊  --  这么牛逼推理个a股走势啊',
 '99  --  这是  --  牛逼 啥玩意儿  --  这不是第四名 牛逼  --  然后倒放视频 说话声音不能再小点  --  这难评  --  盗月社杨树梢女士  --  盗月社杨树梢女士 算是文生视频  --  算是文生视频  --  算是文生视频 这是  --  蜥蜴人 gpt商店',
 '100  --  bgm抄袭的  --  的声音  --  把家里的天花板充分利用起来  --  明明有真实的世界 还要去花心思创造无限接近真实的世界  --  拍什么广告 一段文字的事  --  有望部分解决缺少mc的最高配置 朋友  --  把家里的天花板充分利用起来 gpt  --  朋友  --  才这么穿的吧 敢说擅长数学  --  才这么穿的吧',
 '101  --  2的能力已经超过部份人类了  --  现实世界与虚拟世界的界限打破了  --  要来了么真实的人类  --  米哈游的脑机接口怎么样了 画动画的失业了  --  自由的日子对小扎来说不多了 猴子长了鸟的尾巴  --  科幻电影里的情节越来越近了 要来了么真实的人类  --  螃蟹的脚变成章鱼触手了 活在梦里的时代来临了  --  科幻电影里的情节越来越近了  --  要来了么真实的人类 真正的vtuber要来了  --  这下科普博主有的忙了',
 '102  --  太牛逼了  --  文生视频对于普通人还是太遥远了  --  视频加速了  --  牛了 这可牛逼了  --  脑袋有点扭过了  --  盲猜视频加速了  --  视频加速了 太牛逼了  --  盲猜视频加速了 视频加速了  --  视频加速了 视频加速了  --  脑袋有点扭过了 招了个gpt来上班',
 '103  --  20元一个月很贵吗  --  教师要失业啦吗  --  这能叫特效吗  --  能算出下一期双色球吗 泥哥机器人能采棉花吗  --  这样怎么赶超啊 一定要变秃才能变强吗  --  美西方只会吹牛 它会放神圣电音吗  --  这算双叉臂吗 20元一个月很贵吗  --  美西方只会吹牛  --  这能叫特效吗 刚才那个是席恩吗  --  避免中国零件吗',
 '104  --  github上有游戏工程文件的  --  按现在的市价确实不贵 坐小孩那桌  --  碰运气不就是摄影的魅力所在吗 聚合时候的效果不咋地  --  章北海行为 章北海official行为  --  章北海official行为  --  聚合时候的效果不咋地 不合适的  --  章北海行为  --  甚至想象不出他们的描述语言 刚刚人和树的比例不对  --  聚合时候的效果不咋地  --  猫的右腿看起来不自然 假的好真比例不对',
 '105  --  mj加它会非常好用  --  认知 会不会咬人  --  会不会咬人  --  只有猫妖反对  --  会忘掉底层数据结构 逐渐沦为骗子公司  --  故意写错会怎么样  --  会不会咬人 看看它走路会不会原地踏步  --  故意写错会怎么样 会不会不耐烦  --  会不会不耐烦 认知  --  会不会不耐烦',
 '106  --  imgui  --  钢铁侠  --  233  --  数字  --  操作手机 最好是动口不动手  --  小亮 这是水猴子  --  操作手机  --  安全问题早在2017应该是  --  搞得跟真的一样  --  数字 钢铁侠',
 '107  --  你倒是拿一个有同等水平的ai给我们看看 你做得到吗  --  王德发  --  李春姬  --  就这 你倒是拿一个有同等水平的ai给我们看看  --  小鼠偷拍 alphagozero  --  小鼠偷拍  --  你做得到吗 小鼠偷拍  --  你做得到吗  --  王德发 花钱赎罪  --  你倒是拿一个有同等水平的ai给我们看看',
 '108  --  巨人  --  因为这就是gpt的声音  --  这稿子就是gpt语音念的吧  --  这稿子就是gpt语音念的吧 这视频就是gpt的配音  --  这视频就是gpt的配音 这跟直接网上下的模型库也没啥区别啊  --  这绝对的远程操控机器人  --  这跟直接网上下的模型库也没啥区别啊 这不是国内的河图嘛  --  这视频就是gpt的配音  --  这确实要感谢bbc国家地理探索频道这些年收集的影像数据 这就是七匹狼的新广告  --  这跟直接网上下的模型库也没啥区别啊',
 '109  --  nb nb  --  nb  --  打杂差不多 nb  --  打杂差不多  --  塑料閃電 nb  --  塑料閃電  --  nb 打杂差不多  --  nb 塑料閃電  --    --  ',
 '110  --  1千根  --  1千根 1千根  --  1千根 1万根  --  1万根 1千根  --  1万根  --  小孩手指头巨诡异 1千根  --  小孩手指头巨诡异  --    --    --  ',
 '111  --  哈哈哈 哈哈哈  --  哈哈哈哈哈哈  --  哈哈哈哈哈哈哈哈哈  --  哈哈哈 哈哈哈哈哈哈  --  哈哈哈哈哈哈 哈哈哈哈哈哈  --  哈哈哈 哈哈哈哈哈哈哈哈哈  --  哈哈哈哈哈哈 哈哈哈  --  哈哈哈哈哈哈哈哈哈哈哈哈 哈哈哈哈哈哈  --  哈哈哈尬住  --  哈哈哈尬住 呵呵哈哈哈',
 '112  --  太想进步了 8b  --  未来绝对好莱坞要用上 谷歌新闻否不看了  --  小成本暂时够用了 未来绝对好莱坞要用上  --  小成本暂时够用了  --  想跟机器人过  --  往高了吹  --  感觉是录了一段视频  --  懂了 动嘴不行  --  完了 太强了  --  失业了 西部世界能够实现了',
 '113  --  疯狂  --  这太疯狂了  --  竟然对上了  --  这不止元宇宙  --  这不得不感叹 疯狂  --  而不是老鼠自己走了一遍 他还会开玩笑  --  这不得不感叹  --  绝了 把前面这几个合起来  --  蝴蝶冲到水下去了  --  这不止元宇宙 都要入侵现实了',
 '114  --  加入光荣的进化吧  --  一个还在逐渐淘汰传真机的国家考虑用chatgpt  --  那也不要没有意义的找bug  --  这些应该不是个人电脑上能生成的吧 拍戏的时候也经常用假雪  --  还真是gpt4的声音  --  这是gbt的声音吧 假的吧  --  这些应该不是个人电脑上能生成的吧  --  跟手不是自己的一样 加入光荣的进化吧  --  这是gbt的声音吧  --  跟手不是自己的一样',
 '115  --  bbc滤镜  --  马斯克太牛了  --  这里小腿变换了一下  --  这里小腿变换了一下 卧槽  --  这个太酷了 卧槽有内味了  --  这牛比了 bgm太吵了  --  蒸汽大象  --  老美牛逼了  --  震惊到了  --  震惊到了 它逐渐苏醒了',
 '116  --  ab这类的明星要失业了吧  --  这里应该采样了蜜蜂总动员最后法庭上的那一幕 最后踩没了过马路的人  --  钢铁侠的贾维斯要出来了  --  本来一个按钮的事变成敲了几十下 科技的进步已经没有黑绿棕什么事了  --  机器人终于要成为真正的机器人了  --  机器人终于要成为真正的机器人了 ds开源了导致的  --  模型把人脑里面想象的东西生成出来了  --  模型把人脑里面想象的东西生成出来了 这里应该采样了蜜蜂总动员最后法庭上的那一幕  --  比凶凶的编制老师好多了  --  比凶凶的编制老师好多了 但是几个世纪后的未来见证不到了',

In [30]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1908,-1_凑合_magi_magi magi_新效转换改做超越本质,"[凑合, magi, magi magi, 新效转换改做超越本质, 凑合 凑合, 穿越者, ...",[我觉得不用三年，估计很多视频软件，剪辑软件，PS工具，文书软件，甚至写代码的工具，都可以滚...
1,0,497,0_生快 生快_协同 协同_协同_metaxr metaxr,"[生快 生快, 协同 协同, 协同, metaxr metaxr, 生快, 抢票 抢票, m...","[协同, 协同, 协同]"
2,1,339,1_公平_公平 公平_底特律 变人_愚者抬杠,"[公平, 公平 公平, 底特律 变人, 愚者抬杠, 人工, 别这样, 4万人民币, 罗老师,...","[奈何本人没文化，一句我操走天下，以能为人作我师，谦虚下功学知识。机器，机器呀, 注定不能完..."
3,2,220,2_坐云上_假新闻_what_宇智波家族,"[坐云上, 假新闻, what, 宇智波家族, 清明节蹦迪, 管泽元 se4, 宇智波家族 ...","[假新闻？, 坐云上？, 坐云上？]"
4,3,159,3_ai助手_ai助手 ai助手_ai就是未来_ai工具,"[ai助手, ai助手 ai助手, ai就是未来, ai工具, 反人类组织用ai搞破坏怎办 ...","[现在AI只是拿资料去训练它...逻辑工程, AI工具：GPT-SoVITS, AI开发游戏..."
...,...,...,...,...,...
426,425,10,425_程序员这不是有工作了_程序员这不是有工作了 这就别拿出来秀了罢_这我们不得上红毯礼仪...,"[程序员这不是有工作了, 程序员这不是有工作了 这就别拿出来秀了罢, 这我们不得上红毯礼仪小...","[这勺子跟变魔术一样就出来了, 这东西是不是该驱动就可以了, 这就别放出来了]"
427,426,10,426_卷的觉都睡不好_卷的觉都睡不好 他们都不接马斯克的梗哈哈_阿瓦隆系统这类的每个平台都...,"[卷的觉都睡不好, 卷的觉都睡不好 他们都不接马斯克的梗哈哈, 阿瓦隆系统这类的每个平台都有...","[阿瓦隆系统这类的每个平台都有, 用过都知道-4输出有点慢的, 潜台词：每个国家都要采购我们..."
428,427,10,427_美帝核心科技_文明才能掌握科技_科技属于文明_核心科技 美帝核心科技,"[美帝核心科技, 文明才能掌握科技, 科技属于文明, 核心科技 美帝核心科技, 感谢科技 美...","[科技垃圾, 美帝核心科技, 美帝核心科技]"
429,428,10,428_所以sora搞出来没有_玩呢_没男人_没化妆 任何事情,"[所以sora搞出来没有, 玩呢, 没男人, 没化妆 任何事情, 没化妆, 显的有点变态了 ...","[失业？新就业方向, 玩呢？相差这么多, 任何事情？变个卡车doge]"
430,429,10,429_这下不用封禁ip啦_元宇宙不再遥远 三次元老婆指日可待_元宇宙 还元宇宙_元宇宙必备,"[这下不用封禁ip啦, 元宇宙不再遥远 三次元老婆指日可待, 元宇宙 还元宇宙, 元宇宙必备...","[人类太伟大, 元宇宙必备, 元宇宙不再遥远]"