# 1. La librairie Polars

Laura Darenne, laura.darenne@inalco.fr

## 1.1. Rappel sur la création d'un environnement

Pour créer un environnement python : `python -m venv env_name`.

Pour activer l'environnement : `source env_name/bin/activate`.

Pour afficher toutes les librairies et les dépendances téléchargées dans l'environnement : `pip freeze`.

Pour désactiver l'environnement : `deactivate`.

Pour supprimer un environnement : `rm -r env_name`.

## 1.2. Installation de la librairie polars

Pour installer la librairie polars : `pip install "polars[all]"`.

Pour importer la librairie : `import polars as pl`.

## 1.3. Rappel des différents types de fichiers

### CSV, *Comma-separated values*

Un fichier CSV est un fichier texte où les valeurs sont séparées par des virgules. Chaque ligne correspond à une information.

```csv
Nom,Âge,Ville
Alice,30,Paris
Bob,25,Lyon
```

### TSV, *Tab-separated values*

Un fichier TSV est similaire à un CSV, mais les valeurs sont séparées par des tabulations au lieu de virgules.

```tsv
Nom   Âge    Ville
Alice  30    Paris
Bob    25    Lyon
```

### JSON, *JavaScript Object Notation*

JSON est à l'origine un format de données textuel dérivé de la notation des objets du langage JavaScript. C'est un format léger d'échange de données, facile à lire et à écrire pour les humains, et facile à analyser et à générer pour les machines. Il est basé sur une collection de paires clé/valeur.

```json
[
  {"Nom": "Alice", "Âge": 30, "Ville": "Paris"},
  {"Nom": "Bob", "Âge": 25, "Ville": "Lyon"}
]
```

### JSONL, *JSON Lines*

JSONL est un format où chaque ligne est un objet JSON. C'est utile pour traiter des flux de données ou des fichiers volumineux.

```json
{"Nom": "Alice", "Âge": 30, "Ville": "Paris"}
{"Nom": "Bob", "Âge": 25, "Ville": "Lyon"}
```

## 1.4. Polars, Pandas et les dataframes

Les dataframes sont une structure de données utilisée pour organiser, manipuler et stocker des données de manière tabulaire, similaire à une feuille de calcul ou à une table dans une base de données relationnelle.

1. Un dataframe est composé de lignes et de colonnes corresondant à des *observations* et à des *séries*.
2. Les colonnes d'un dataframe peuvent contenir des types de données différents : des entiers, des flottants, des chaînes de caractères, etc.
3. Les dataframes offrent des méthodes intégrées pour filtrer, trier, agréger, fusionner et joindre des données, ce qui rend la manipulation des données plus intuitive et plus rapide.
4. Les dataframes sont compatibles avec de nombreux formats de données, y compris CSV, JSON, Excel, SQL, etc., ce qui facilite l'importation et l'exportation de données.
5. Les dataframes sont souvent utilisés dans l'analyse des données car ils permettent de calculer facilement des statistiques descriptives, de gérer les valeurs manquantes, et de visualiser les données.

## 1.5. Pourquoi utilisé cela plutôt que d'ouvrir le fichier avec la fonction `with open()` ?

Polars est codé en `Rust` et a été conçu pour simplifier la lecture, l'écriture et la manipulation des données (parfois en quantité importante). Polars exploite les calculs parallèles pour traiter rapidement de grandes quantités de données alors que `with open()` nécessite de parcourir les fichiers ligne par ligne ce qui est moins efficace pour les gros volumes de données.

Les dataframes permettent aussi tout une panoplie d'outils pour la manipulation des données : le filtrage, le tri, l'agrégation, et la transformation. Ils gèrent automatiquement les types de données (et leurs erreurs associées) alors que `with open()` nécessite une conversion manuelle des types de données à partir des chaînes de caractères lues. 

Les dataframes sont également compatibles avec de nombreux outils (comprendre librairies) d'analyse et de visualisation.

# 2. Et tout de suite le TP

In [1]:
import polars as pl

## 2.1. Créer un dataframe

In [2]:
# à partir d'un dictionnaire
tableau = {
    'A': [1, 2, 3], 
    'B': ['a', 'b', 'c'], 
    'C': [[1, 2], [3, 4], [5, 6]]
}
df = pl.DataFrame(tableau)
df

shape: (3, 3)
┌─────┬─────┬───────────┐
│ A   ┆ B   ┆ C         │
│ --- ┆ --- ┆ ---       │
│ i64 ┆ str ┆ list[i64] │
╞═════╪═════╪═══════════╡
│ 1   ┆ a   ┆ [1, 2]    │
│ 2   ┆ b   ┆ [3, 4]    │
│ 3   ┆ c   ┆ [5, 6]    │
└─────┴─────┴───────────┘

In [3]:
# à partir d'une liste de dictionnaire
tableau = [
    {'A': 1, 'B': 'a'}, 
    {'A': 2, 'B': 'b'},
    {'A': 3, 'B': 'c'}
]
df = pl.DataFrame(tableau)
df

shape: (3, 2)
┌─────┬─────┐
│ A   ┆ B   │
│ --- ┆ --- │
│ i64 ┆ str │
╞═════╪═════╡
│ 1   ┆ a   │
│ 2   ┆ b   │
│ 3   ┆ c   │
└─────┴─────┘

## 2.2. Découverte des données


2 fichiers CSV :
- comments.csv
- videos.csv

Pour ouvrir un fichier avec Polars, vous pouvez vous référer à la documentation ici : https://docs.pola.rs/api/python/stable/reference/io.html

Un fichier CSV s'ouvre comme ceci :

In [4]:
df = pl.read_csv('videos.csv', separator=',')
df.head() # permet de n'observer que les 5 premières lignes

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ video_id  ┆ video_tit ┆ published ┆ channel_i ┆ … ┆ comment_c ┆ has_capti ┆ category  ┆ tags     │
│ ---       ┆ le        ┆ _at       ┆ d         ┆   ┆ ount      ┆ ons       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str      │
│           ┆ str       ┆ str       ┆ str       ┆   ┆ i64       ┆ bool      ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1_UCKSs88 ┆ ÉTAT DE   ┆ 2025-01-1 ┆ UC9hHeywc ┆ … ┆ 749       ┆ false     ┆ News &    ┆ trump|ma │
│ fw        ┆ LA        ┆ 9T16:45:5 ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ cron|inv │
│           ┆ FRANCE :  ┆ 3Z        ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ estiture │
│           ┆ CE        ┆           ┆           ┆   ┆           ┆           ┆           ┆ |bayro…  │
│           ┆ MENSONG…  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Hc9UD6iil ┆ FRANCE :  ┆ 2024-12-2 ┆ UC9hHeywc ┆ … ┆ 566       ┆ false     ┆ News &    ┆ macron|b │
│ NY        ┆ LA        ┆ 2T16:30:0 ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ ayrou|1e │
│           ┆ SITUATION ┆ 4Z        ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ r minist │
│           ┆ POLITIQU… ┆           ┆           ┆   ┆           ┆           ┆           ┆ re|que…  │
│ -32lgROAm ┆ QUI VEUT  ┆ 2024-11-2 ┆ UC9hHeywc ┆ … ┆ 696       ┆ false     ┆ News &    ┆ agricult │
│ DQ        ┆ LA PEAU   ┆ 5T16:37:2 ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ eur|en   │
│           ┆ DES AGRIC ┆ 3Z        ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ colère|a │
│           ┆ ULTE…     ┆           ┆           ┆   ┆           ┆           ┆           ┆ gricult… │
│ BI_fweGoR ┆ TRUMP     ┆ 2024-11-1 ┆ UC9hHeywc ┆ … ┆ 1327      ┆ false     ┆ News &    ┆ trump|el │
│ JU        ┆ RÉÉLU :   ┆ 2T16:29:4 ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ on musk| │
│           ┆ QUELLES   ┆ 4Z        ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ tesla|st │
│           ┆ IMPLICAT… ┆           ┆           ┆   ┆           ┆           ┆           ┆ arligh…  │
│ D1pQ6c1T8 ┆ MOLDAVIE, ┆ 2024-10-3 ┆ UC9hHeywc ┆ … ┆ 1206      ┆ false     ┆ News &    ┆ macron|b │
│ X4        ┆ GÉORGIE,  ┆ 1T16:37:1 ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ arnier|é │
│           ┆ BRICS :   ┆ 0Z        ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ conomie| │
│           ┆ L'E…      ┆           ┆           ┆   ┆           ┆           ┆           ┆ budget…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

#### Le fichier videos.csv

Le fichier *videos.csv* est composé des metadonnées de vidéos extraits de YouTube. Il est composé comme ceci.

|Variable|Description|Type|
|:-:|:-|:-:|
|*video_id*|identifiant unique donné par YouTube à la vidéo|String|
|*video_title*|titre de la vidéo|String|
|*published_at*|date et heure de publication à l'origine au format ISO 8601 mais transformé juste après au format Datetime|Datetime|
|*channel_id*|identifiant unique donné par YouTube à la chaîne|String|
|*view_count, like_count, comment_count*|nombre de vues, likes, commentaires de la vidéo|Int64|
|*has_captions*|True si il y a une transcription|Bool|
|*category*|nom de la catégorie donné par le youtubeur|String|
|*tags*|liste de mots choisis par le youtubeur, s’il le souhaite, pour décrire la vidéo|String|

Le format de date ISO 8601 se compose comme ceci :
- `2024-07-16T16:07:10Z`
- `annee-mois-joursTheures:minutes:secondesZ`

`datetime` est un format python pour la manipulation des dates et des heures.

In [5]:
df = df.with_columns(
    pl.col('published_at').str.to_datetime()
) # transforme le type de la colonne 'published_at' de string à datetime
df.head()

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ video_id  ┆ video_tit ┆ published ┆ channel_i ┆ … ┆ comment_c ┆ has_capti ┆ category  ┆ tags     │
│ ---       ┆ le        ┆ _at       ┆ d         ┆   ┆ ount      ┆ ons       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str      │
│           ┆ str       ┆ datetime[ ┆ str       ┆   ┆ i64       ┆ bool      ┆           ┆          │
│           ┆           ┆ μs, UTC]  ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1_UCKSs88 ┆ ÉTAT DE   ┆ 2025-01-1 ┆ UC9hHeywc ┆ … ┆ 749       ┆ false     ┆ News &    ┆ trump|ma │
│ fw        ┆ LA        ┆ 9         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ cron|inv │
│           ┆ FRANCE :  ┆ 16:45:53  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ estiture │
│           ┆ CE        ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ |bayro…  │
│           ┆ MENSONG…  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Hc9UD6iil ┆ FRANCE :  ┆ 2024-12-2 ┆ UC9hHeywc ┆ … ┆ 566       ┆ false     ┆ News &    ┆ macron|b │
│ NY        ┆ LA        ┆ 2         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ ayrou|1e │
│           ┆ SITUATION ┆ 16:30:04  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ r minist │
│           ┆ POLITIQU… ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ re|que…  │
│ -32lgROAm ┆ QUI VEUT  ┆ 2024-11-2 ┆ UC9hHeywc ┆ … ┆ 696       ┆ false     ┆ News &    ┆ agricult │
│ DQ        ┆ LA PEAU   ┆ 5         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ eur|en   │
│           ┆ DES AGRIC ┆ 16:37:23  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ colère|a │
│           ┆ ULTE…     ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ gricult… │
│ BI_fweGoR ┆ TRUMP     ┆ 2024-11-1 ┆ UC9hHeywc ┆ … ┆ 1327      ┆ false     ┆ News &    ┆ trump|el │
│ JU        ┆ RÉÉLU :   ┆ 2         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ on musk| │
│           ┆ QUELLES   ┆ 16:29:44  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ tesla|st │
│           ┆ IMPLICAT… ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ arligh…  │
│ D1pQ6c1T8 ┆ MOLDAVIE, ┆ 2024-10-3 ┆ UC9hHeywc ┆ … ┆ 1206      ┆ false     ┆ News &    ┆ macron|b │
│ X4        ┆ GÉORGIE,  ┆ 1         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ arnier|é │
│           ┆ BRICS :   ┆ 16:37:10  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ conomie| │
│           ┆ L'E…      ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ budget…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Pour sélectionner une colonne, une série, et travailler sur un objet polars.series

In [6]:
df["video_id"]

shape: (370,)
Series: 'video_id' [str]
[
	"1_UCKSs88fw"
	"Hc9UD6iilNY"
	"-32lgROAmDQ"
	"BI_fweGoRJU"
	"D1pQ6c1T8X4"
	…
	"vxZ6U0Njc6M"
	"WPbT04SgpzY"
	"e3MvTSKhcLA"
	"PTM5AzmhmNk"
	"Gx75guyRGJY"
]

In [7]:
type(df["video_id"])

polars.series.series.Series

Pour sélectionner plusieurs colonnes, ou même une colonne mais garder un objet polars.dataframe

In [8]:
df.select(["video_id", "video_title"])

shape: (370, 2)
┌─────────────┬─────────────────────────────────┐
│ video_id    ┆ video_title                     │
│ ---         ┆ ---                             │
│ str         ┆ str                             │
╞═════════════╪═════════════════════════════════╡
│ 1_UCKSs88fw ┆ ÉTAT DE LA FRANCE : CE MENSONG… │
│ Hc9UD6iilNY ┆ FRANCE : LA SITUATION POLITIQU… │
│ -32lgROAmDQ ┆ QUI VEUT LA PEAU DES AGRICULTE… │
│ BI_fweGoRJU ┆ TRUMP RÉÉLU : QUELLES IMPLICAT… │
│ D1pQ6c1T8X4 ┆ MOLDAVIE, GÉORGIE, BRICS : L'E… │
│ …           ┆ …                               │
│ vxZ6U0Njc6M ┆ [Fil d'Actu #04] Le froid tue,… │
│ WPbT04SgpzY ┆ [Fil d'Actu #03] Air France, T… │
│ e3MvTSKhcLA ┆ [Fil d'Actu #02] Syrie, Police… │
│ PTM5AzmhmNk ┆ [Fil d'Actu spécial] Air Franc… │
│ Gx75guyRGJY ┆ [Fil d'Actu #01] Volkswagen, O… │
└─────────────┴─────────────────────────────────┘

In [9]:
type(df.select(["video_id", "video_title"]))

polars.dataframe.frame.DataFrame

## 2.3. Jouer avec les séries et les observations

Vous pouvez aussi obtenir la liste des noms de colonnes :

In [10]:
df.columns

['video_id',
 'video_title',
 'published_at',
 'channel_id',
 'view_count',
 'like_count',
 'comment_count',
 'has_captions',
 'category',
 'tags']

In [11]:
type(df.columns)

list

La taille de votre dataframe :

In [12]:
df.shape

(370, 10)

In [13]:
type(df.shape)

tuple

Le nombre d'observations :

In [14]:
df.height

370

In [15]:
type(df.height)

int

Le nombre de séries :

In [16]:
df.width

10

Chaque série (colonne) peut être interrogée individuellement comme ceci :

In [17]:
df["video_id"]

shape: (370,)
Series: 'video_id' [str]
[
	"1_UCKSs88fw"
	"Hc9UD6iilNY"
	"-32lgROAmDQ"
	"BI_fweGoRJU"
	"D1pQ6c1T8X4"
	…
	"vxZ6U0Njc6M"
	"WPbT04SgpzY"
	"e3MvTSKhcLA"
	"PTM5AzmhmNk"
	"Gx75guyRGJY"
]

In [18]:
type(df["video_id"])

polars.series.series.Series

La technique du slicing permet d'accéder à des observations :

In [19]:
df[8:78]

shape: (70, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ video_id  ┆ video_tit ┆ published ┆ channel_i ┆ … ┆ comment_c ┆ has_capti ┆ category  ┆ tags     │
│ ---       ┆ le        ┆ _at       ┆ d         ┆   ┆ ount      ┆ ons       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str      │
│           ┆ str       ┆ datetime[ ┆ str       ┆   ┆ i64       ┆ bool      ┆           ┆          │
│           ┆           ┆ μs, UTC]  ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 8gR67m5pP ┆ DÉFICIT : ┆ 2024-09-2 ┆ UC9hHeywc ┆ … ┆ 2163      ┆ false     ┆ News &    ┆ déficit| │
│ ak        ┆ C'EST     ┆ 9         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ dette|ta │
│           ┆ PIRE QUE  ┆ 16:04:15  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ ux|empru │
│           ┆ VOUS …    ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ nt|tou…  │
│ MaIE5_apZ ┆ 🔥 MICHEL ┆ 2024-09-1 ┆ UC9hHeywc ┆ … ┆ 966       ┆ false     ┆ News &    ┆ Le Fil   │
│ _Q        ┆ BARNIER : ┆ 8         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ d'actu|T │
│           ┆ UN        ┆ 16:16:46  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ atiana   │
│           ┆ PYROMANE… ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ Ventose| │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ YffVoIf7u ┆ COMMENT   ┆ 2024-07-1 ┆ UC9hHeywc ┆ … ┆ 1678      ┆ true      ┆ News &    ┆ macron|g │
│ BU        ┆ MACRON A  ┆ 6         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ ouvernem │
│           ┆ RÉUSSI    ┆ 16:07:10  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ ent|légi │
│           ┆ SON CO…   ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ slativ…  │
│ _iK-2IeXe ┆ LÉGISLATI ┆ 2024-07-0 ┆ UC9hHeywc ┆ … ┆ 2698      ┆ false     ┆ News &    ┆ crise|ma │
│ s0        ┆ VES :     ┆ 5         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ jorité|1 │
│           ┆ L'ANALYSE ┆ 16:53:06  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ er minis │
│           ┆ QUE V…    ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ tre|ba…  │
│ 7Wizb0Sji ┆ ⚠️ EXCLUS ┆ 2024-06-2 ┆ UC9hHeywc ┆ … ┆ 3184      ┆ false     ┆ News &    ┆ législat │
│ go        ┆ IF⚠️ ON   ┆ 8         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ ives|rés │
│           ┆ VOUS      ┆ 16:06:28  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ ultats|d │
│           ┆ RÉVÈLE Q… ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ éputé|…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 9NOA2kBgq ┆ VACCINATI ┆ 2021-03-1 ┆ UC9hHeywc ┆ … ┆ 1294      ┆ false     ┆ News &    ┆ vaccin|c │
│ 2U        ┆ ON :      ┆ 1         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ ovid|vac │
│           ┆ CHRONIQUE ┆ 17:54:21  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ cinés|pé │
│           ┆ D'UN F…   ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ nurie|…  │
│ 9etzp2v_I ┆ DÉPRESSIO ┆ 2021-03-0 ┆ UC9hHeywc ┆ … ┆ 872       ┆ false     ┆ News &    ┆ étudiant │
│ vg        ┆ N, PRÉCAR ┆ 4         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ s|fantôm │
│           ┆ ITÉ : AUX ┆ 17:35:44  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ e|précar │
│           ┆ RA…       ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ ité|mc…  │
│ _kwag-5gq ┆ ITALIE :  ┆ 2021-02-1 ┆ UC9hHeywc ┆ … ┆ 1706      ┆ false     ┆ News &    ┆ italie|d │
│ W0        ┆ LA DÉMOCR ┆ 9         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ raghi|ue │
│           ┆ ATIE      ┆ 16:40:17  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ |union   │
│           ┆ PIÉTINÉ…  ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ europée… │
│ 5o0NrNh3l ┆ APRÈS LA  ┆ 2021-02-1 ┆ UC9hHeywc ┆ … ┆ 2028      ┆ false     ┆ News &    ┆ crise|co │
│ KU        ┆ COVID,    ┆ 1         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ vid|chom │
│           ┆ L'EFFONDR ┆ 18:41:43  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ age|étud │
│           ┆ EMENT…    ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ iants|…  │
│ C141jgHpr ┆ LA FRANCE ┆ 2021-02-0 ┆ UC9hHeywc ┆ … ┆ 2812      ┆ false     ┆ News &    ┆ covid|co │
│ YI        ┆ DIRIGÉE   ┆ 6         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ nfinemen │
│           ┆ PAR DES   ┆ 16:16:02  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ t|reconf │
│           ┆ SADI…     ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ inemen…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## 2.4. Filtres
Vous pouvez aussi filtrer les observations :

In [20]:
df.filter(pl.col("has_captions") == True)

shape: (79, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ video_id  ┆ video_tit ┆ published ┆ channel_i ┆ … ┆ comment_c ┆ has_capti ┆ category  ┆ tags     │
│ ---       ┆ le        ┆ _at       ┆ d         ┆   ┆ ount      ┆ ons       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str      │
│           ┆ str       ┆ datetime[ ┆ str       ┆   ┆ i64       ┆ bool      ┆           ┆          │
│           ┆           ┆ μs, UTC]  ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ YffVoIf7u ┆ COMMENT   ┆ 2024-07-1 ┆ UC9hHeywc ┆ … ┆ 1678      ┆ true      ┆ News &    ┆ macron|g │
│ BU        ┆ MACRON A  ┆ 6         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ ouvernem │
│           ┆ RÉUSSI    ┆ 16:07:10  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ ent|légi │
│           ┆ SON CO…   ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ slativ…  │
│ 1Lkpj6wOr ┆ NON, LE   ┆ 2024-06-0 ┆ UC9hHeywc ┆ … ┆ 721       ┆ true      ┆ News &    ┆ gabriel  │
│ 6I        ┆ MARCHÉ    ┆ 5         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ attal|jo │
│           ┆ UNIQUE    ┆ 16:05:50  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ rdan bar │
│           ┆ EUROPÉEN… ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ della|…  │
│ zcv-SjUf5 ┆ AGRICULTU ┆ 2024-02-1 ┆ UC9hHeywc ┆ … ┆ 608       ┆ true      ┆ News &    ┆ agricult │
│ 8I        ┆ RE 🇫🇷 :   ┆ 8         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ eurs|agr │
│           ┆ L’IMPASSE ┆ 17:05:08  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ iculteur │
│           ┆ MON…      ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ |bio|s…  │
│ NbDjt8w7n ┆ POUR EN   ┆ 2023-11-3 ┆ UC9hHeywc ┆ … ┆ 1122      ┆ true      ┆ News &    ┆ macron|t │
│ zE        ┆ FINIR     ┆ 0         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ atiana   │
│           ┆ AVEC LES  ┆ 16:30:05  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ ventose| │
│           ┆ ÉOLIENN…  ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ greta t… │
│ I9kNkrkuF ┆ RELANCER  ┆ 2023-08-3 ┆ UC9hHeywc ┆ … ┆ 61        ┆ true      ┆ News &    ┆ Fil d'ac │
│ Bg        ┆ UNE PRODU ┆ 1         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ tu|tommy │
│           ┆ CTION     ┆ 15:30:09  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ lasserre │
│           ┆ NATION…   ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ |jacq…   │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ LE2OH6Oa8 ┆ [Fil      ┆ 2016-05-0 ┆ UC9hHeywc ┆ … ┆ 85        ┆ true      ┆ Entertain ┆ violence │
│ ho        ┆ d'Actu    ┆ 5         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ ment      ┆ s polici │
│           ┆ #29]      ┆ 18:38:03  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ ères|tar │
│           ┆ Violences ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ anis|h…  │
│           ┆ pol…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Vgk_VZ00T ┆ [Fil      ┆ 2016-04-2 ┆ UC9hHeywc ┆ … ┆ 55        ┆ true      ┆ Entertain ┆ Mc Do|Mc │
│ 0o        ┆ d'Actu    ┆ 8         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ ment      ┆ Donald's │
│           ┆ #28] Mc   ┆ 17:12:17  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ |McDonal │
│           ┆ Donald's, ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ d|fas…   │
│           ┆ …         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ zYks0I4d_ ┆ [Fil      ┆ 2016-04-2 ┆ UC9hHeywc ┆ … ┆ 38        ┆ true      ┆ Entertain ┆ Luxleaks │
│ oE        ┆ d'Actu    ┆ 1         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ ment      ┆ |Panama  │
│           ┆ #27]      ┆ 18:42:20  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ Papers|A │
│           ┆ Secret    ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ ntoine…  │
│           ┆ des af…   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ AOVf3s-c0 ┆ [Fil      ┆ 2016-04-1 ┆ UC9hHeywc ┆ … ┆ 93        ┆ true      ┆ News &    ┆ Nuit     │
│ fM        ┆ d'Actu    ┆ 3         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ Debout   │
│           ┆ spécial]  ┆ 11:48:10  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆          │
│           ┆ Nuit      ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ Debo…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GXJXq7B3I ┆ [Fil      ┆ 2016-03-3 ┆ UC9hHeywc ┆ … ┆ 52        ┆ true      ┆ News &    ┆ Bernie   │
│ 60        ┆ d'Actu    ┆ 1         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ Sanders| │
│           ┆ #24]      ┆ 18:34:20  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ Donald   │
│           ┆ Elections ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ Trump|Hi │
│           ┆ US …      ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [21]:
from datetime import datetime, timezone
df.filter(pl.col("published_at") > datetime(2023, 1, 2, tzinfo=timezone.utc))

shape: (31, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ video_id  ┆ video_tit ┆ published ┆ channel_i ┆ … ┆ comment_c ┆ has_capti ┆ category  ┆ tags     │
│ ---       ┆ le        ┆ _at       ┆ d         ┆   ┆ ount      ┆ ons       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str      │
│           ┆ str       ┆ datetime[ ┆ str       ┆   ┆ i64       ┆ bool      ┆           ┆          │
│           ┆           ┆ μs, UTC]  ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1_UCKSs88 ┆ ÉTAT DE   ┆ 2025-01-1 ┆ UC9hHeywc ┆ … ┆ 749       ┆ false     ┆ News &    ┆ trump|ma │
│ fw        ┆ LA        ┆ 9         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ cron|inv │
│           ┆ FRANCE :  ┆ 16:45:53  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ estiture │
│           ┆ CE        ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ |bayro…  │
│           ┆ MENSONG…  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Hc9UD6iil ┆ FRANCE :  ┆ 2024-12-2 ┆ UC9hHeywc ┆ … ┆ 566       ┆ false     ┆ News &    ┆ macron|b │
│ NY        ┆ LA        ┆ 2         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ ayrou|1e │
│           ┆ SITUATION ┆ 16:30:04  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ r minist │
│           ┆ POLITIQU… ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ re|que…  │
│ -32lgROAm ┆ QUI VEUT  ┆ 2024-11-2 ┆ UC9hHeywc ┆ … ┆ 696       ┆ false     ┆ News &    ┆ agricult │
│ DQ        ┆ LA PEAU   ┆ 5         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ eur|en   │
│           ┆ DES AGRIC ┆ 16:37:23  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ colère|a │
│           ┆ ULTE…     ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ gricult… │
│ BI_fweGoR ┆ TRUMP     ┆ 2024-11-1 ┆ UC9hHeywc ┆ … ┆ 1327      ┆ false     ┆ News &    ┆ trump|el │
│ JU        ┆ RÉÉLU :   ┆ 2         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ on musk| │
│           ┆ QUELLES   ┆ 16:29:44  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ tesla|st │
│           ┆ IMPLICAT… ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ arligh…  │
│ D1pQ6c1T8 ┆ MOLDAVIE, ┆ 2024-10-3 ┆ UC9hHeywc ┆ … ┆ 1206      ┆ false     ┆ News &    ┆ macron|b │
│ X4        ┆ GÉORGIE,  ┆ 1         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ arnier|é │
│           ┆ BRICS :   ┆ 16:37:10  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ conomie| │
│           ┆ L'E…      ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ budget…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ CEqfd2zDs ┆ NON,      ┆ 2023-07-3 ┆ UC9hHeywc ┆ … ┆ 2256      ┆ false     ┆ News &    ┆ macron|r │
│ xs        ┆ MACRON NE ┆ 1         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ éindustr │
│           ┆ « RÉINDUS ┆ 15:30:05  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ ialisati │
│           ┆ TRIALI…   ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ on|tat…  │
│ sJJY2e9qG ┆ POUR EN   ┆ 2023-07-1 ┆ UC9hHeywc ┆ … ┆ 2078      ┆ false     ┆ News &    ┆ jancovic │
│ oE        ┆ FINIR     ┆ 0         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ i|greta  │
│           ┆ AVEC LES  ┆ 16:00:44  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ thunberg │
│           ┆ ÉOLIENN…  ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ |solai…  │
│ NQvh5_m7_ ┆ ÉCONOMIE  ┆ 2023-04-1 ┆ UC9hHeywc ┆ … ┆ 3176      ┆ false     ┆ News &    ┆ macron|r │
│ -4        ┆ : ILS     ┆ 4         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ etraite| │
│           ┆ NOUS      ┆ 16:00:22  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ pib|écon │
│           ┆ MENTENT   ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ omie|f…  │
│           ┆ DE…       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ NxXaMEQMw ┆ DÉFI AUX  ┆ 2023-04-1 ┆ UC9hHeywc ┆ … ┆ 1370      ┆ false     ┆ News &    ┆ fil d'ac │
│ CQ        ┆ FACT-CHEC ┆ 2         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ tu|tatia │
│           ┆ KEURS     ┆ 16:00:12  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ na vento │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ se|mac…  │
│ -yeOh7b5M ┆ ⚡️ ÉLECTR ┆ 2023-02-0 ┆ UC9hHeywc ┆ … ┆ 1295      ┆ false     ┆ News &    ┆ boulange │
│ 6M        ┆ ICITÉ :   ┆ 7         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ r|factur │
│           ┆ NOS BOULA ┆ 16:00:00  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ es|élect │
│           ┆ NGER…     ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ ricité…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## 2.5. Enregistrer dans un fichier le dataframe

In [22]:
# enregistre le dataframe dans un fichier tsv
df.write_csv("test.tsv", separator="\t")

In [23]:
df.write_json("test.json")

In [24]:
df.write_csv("test.csv")

### Pourquoi ma variable ne renvoie plus le dataframe

La fonction `.write_csv` se contente d'écrire le dataframe dans un fichier. Il ne renvoie rien, au contraire d'autres fonctions polars. Cela fonctionne comme ceci:

In [25]:
df = pl.read_csv("videos.csv").with_columns(
    pl.col('published_at').str.to_datetime()
).write_csv("new_videos.csv")
df # n'affiche pas le dataframe

In [26]:
type(df) # renvoie NoneType ce qui signifie que la variable n'a pas de type, elle est vide

NoneType

In [27]:
def une_fonction_qui_ecrit_dans_un_fichier_et_renvoie_la_variable(var: str) -> str:
    """cette fonction écrit dans un fichier test.txt la variable, 
    puis la renvoie

    var (str): la variable que l'on veut écrire dans un fichier test.txt
    """
    with open("test.txt", "w") as f:
        f.write(var)
    return var

def une_fonction_qui_ecrit_dans_un_fichier_mais_ne_renvoie_rien(var: str) -> None:
    """cette fonction écrit dans un fichier test_new.txt la variable, 
    mais ne la renvoie pas

    var (str): la variable que l'on veut écrire dans un fichier test_new.txt
    """
    with open("test_new.txt", "w") as f:
        f.write(var)

In [28]:
a = une_fonction_qui_ecrit_dans_un_fichier_et_renvoie_la_variable("test a")
b = une_fonction_qui_ecrit_dans_un_fichier_mais_ne_renvoie_rien("test b")

In [29]:
a

'test a'

In [30]:
type(a)

str

In [31]:
b

In [32]:
type(b)

NoneType

La fonction `une_fonction_qui_ecrit_dans_un_fichier_mais_ne_renvoie_rien()` est comme la fonction `.write_csv()`, elle effectue une action mais ne renvoie rien.
Ce qui fait que notre variable qui contenait le dataframe est maintenant vide.

## 2.6. Quelques calculs sur une série

In [33]:
df = pl.read_csv("videos.csv").with_columns(
    pl.col('published_at').str.to_datetime()
)

In [34]:
df["view_count"].sum() # somme des vues

26845410

In [35]:
df["view_count"].mean() # moyenne des vues

72555.16216216216

In [36]:
df["view_count"].std() # écart-type des vues

81487.18742325381

In [37]:
df["view_count"].len() # le nombre d'observations dans la série

370

## 2.7. Modifier les valeurs dans le dataframe

Les modifications se font au sein de la méthode `.with_columns()`.

In [38]:
df = pl.read_csv(
    "videos.csv"
).with_columns(
    pl.col('published_at').str.to_datetime()
) # transforme le type de la colonne 'published_at' de string à datetime
df.head()

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ video_id  ┆ video_tit ┆ published ┆ channel_i ┆ … ┆ comment_c ┆ has_capti ┆ category  ┆ tags     │
│ ---       ┆ le        ┆ _at       ┆ d         ┆   ┆ ount      ┆ ons       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str      │
│           ┆ str       ┆ datetime[ ┆ str       ┆   ┆ i64       ┆ bool      ┆           ┆          │
│           ┆           ┆ μs, UTC]  ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1_UCKSs88 ┆ ÉTAT DE   ┆ 2025-01-1 ┆ UC9hHeywc ┆ … ┆ 749       ┆ false     ┆ News &    ┆ trump|ma │
│ fw        ┆ LA        ┆ 9         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ cron|inv │
│           ┆ FRANCE :  ┆ 16:45:53  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ estiture │
│           ┆ CE        ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ |bayro…  │
│           ┆ MENSONG…  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Hc9UD6iil ┆ FRANCE :  ┆ 2024-12-2 ┆ UC9hHeywc ┆ … ┆ 566       ┆ false     ┆ News &    ┆ macron|b │
│ NY        ┆ LA        ┆ 2         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ ayrou|1e │
│           ┆ SITUATION ┆ 16:30:04  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ r minist │
│           ┆ POLITIQU… ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ re|que…  │
│ -32lgROAm ┆ QUI VEUT  ┆ 2024-11-2 ┆ UC9hHeywc ┆ … ┆ 696       ┆ false     ┆ News &    ┆ agricult │
│ DQ        ┆ LA PEAU   ┆ 5         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ eur|en   │
│           ┆ DES AGRIC ┆ 16:37:23  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ colère|a │
│           ┆ ULTE…     ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ gricult… │
│ BI_fweGoR ┆ TRUMP     ┆ 2024-11-1 ┆ UC9hHeywc ┆ … ┆ 1327      ┆ false     ┆ News &    ┆ trump|el │
│ JU        ┆ RÉÉLU :   ┆ 2         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ on musk| │
│           ┆ QUELLES   ┆ 16:29:44  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ tesla|st │
│           ┆ IMPLICAT… ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ arligh…  │
│ D1pQ6c1T8 ┆ MOLDAVIE, ┆ 2024-10-3 ┆ UC9hHeywc ┆ … ┆ 1206      ┆ false     ┆ News &    ┆ macron|b │
│ X4        ┆ GÉORGIE,  ┆ 1         ┆ PBnLglqnQ ┆   ┆           ┆           ┆ Politics  ┆ arnier|é │
│           ┆ BRICS :   ┆ 16:37:10  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆ conomie| │
│           ┆ L'E…      ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆ budget…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Les modifications apportées peuvent dépendre de la valeur de l'observation :

In [39]:
df = df.with_columns(
    pl.when(pl.col("view_count") > 100000)
    .then(100000)
    .when((pl.col("view_count") < 100000) & (pl.col("view_count") > 50000))
    .then(50000)
    .otherwise(0)
    .alias("a_peu_pres")
)
df

shape: (370, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ video_id  ┆ video_tit ┆ published ┆ channel_i ┆ … ┆ has_capti ┆ category  ┆ tags      ┆ a_peu_pr │
│ ---       ┆ le        ┆ _at       ┆ d         ┆   ┆ ons       ┆ ---       ┆ ---       ┆ es       │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---      │
│           ┆ str       ┆ datetime[ ┆ str       ┆   ┆ bool      ┆           ┆           ┆ i32      │
│           ┆           ┆ μs, UTC]  ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1_UCKSs88 ┆ ÉTAT DE   ┆ 2025-01-1 ┆ UC9hHeywc ┆ … ┆ false     ┆ News &    ┆ trump|mac ┆ 100000   │
│ fw        ┆ LA        ┆ 9         ┆ PBnLglqnQ ┆   ┆           ┆ Politics  ┆ ron|inves ┆          │
│           ┆ FRANCE :  ┆ 16:45:53  ┆ RaNShQ    ┆   ┆           ┆           ┆ titure|ba ┆          │
│           ┆ CE        ┆ UTC       ┆           ┆   ┆           ┆           ┆ yro…      ┆          │
│           ┆ MENSONG…  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Hc9UD6iil ┆ FRANCE :  ┆ 2024-12-2 ┆ UC9hHeywc ┆ … ┆ false     ┆ News &    ┆ macron|ba ┆ 50000    │
│ NY        ┆ LA        ┆ 2         ┆ PBnLglqnQ ┆   ┆           ┆ Politics  ┆ yrou|1er  ┆          │
│           ┆ SITUATION ┆ 16:30:04  ┆ RaNShQ    ┆   ┆           ┆           ┆ ministre| ┆          │
│           ┆ POLITIQU… ┆ UTC       ┆           ┆   ┆           ┆           ┆ que…      ┆          │
│ -32lgROAm ┆ QUI VEUT  ┆ 2024-11-2 ┆ UC9hHeywc ┆ … ┆ false     ┆ News &    ┆ agriculte ┆ 50000    │
│ DQ        ┆ LA PEAU   ┆ 5         ┆ PBnLglqnQ ┆   ┆           ┆ Politics  ┆ ur|en col ┆          │
│           ┆ DES AGRIC ┆ 16:37:23  ┆ RaNShQ    ┆   ┆           ┆           ┆ ère|agric ┆          │
│           ┆ ULTE…     ┆ UTC       ┆           ┆   ┆           ┆           ┆ ult…      ┆          │
│ BI_fweGoR ┆ TRUMP     ┆ 2024-11-1 ┆ UC9hHeywc ┆ … ┆ false     ┆ News &    ┆ trump|elo ┆ 100000   │
│ JU        ┆ RÉÉLU :   ┆ 2         ┆ PBnLglqnQ ┆   ┆           ┆ Politics  ┆ n musk|te ┆          │
│           ┆ QUELLES   ┆ 16:29:44  ┆ RaNShQ    ┆   ┆           ┆           ┆ sla|starl ┆          │
│           ┆ IMPLICAT… ┆ UTC       ┆           ┆   ┆           ┆           ┆ igh…      ┆          │
│ D1pQ6c1T8 ┆ MOLDAVIE, ┆ 2024-10-3 ┆ UC9hHeywc ┆ … ┆ false     ┆ News &    ┆ macron|ba ┆ 100000   │
│ X4        ┆ GÉORGIE,  ┆ 1         ┆ PBnLglqnQ ┆   ┆           ┆ Politics  ┆ rnier|éco ┆          │
│           ┆ BRICS :   ┆ 16:37:10  ┆ RaNShQ    ┆   ┆           ┆           ┆ nomie|bud ┆          │
│           ┆ L'E…      ┆ UTC       ┆           ┆   ┆           ┆           ┆ get…      ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ vxZ6U0Njc ┆ [Fil      ┆ 2015-10-2 ┆ UC9hHeywc ┆ … ┆ false     ┆ People &  ┆ bernie    ┆ 0        │
│ 6M        ┆ d'Actu    ┆ 4         ┆ PBnLglqnQ ┆   ┆           ┆ Blogs     ┆ sanders|h ┆          │
│           ┆ #04] Le   ┆ 00:07:39  ┆ RaNShQ    ┆   ┆           ┆           ┆ iver|sdf| ┆          │
│           ┆ froid     ┆ UTC       ┆           ┆   ┆           ┆           ┆ logem…    ┆          │
│           ┆ tue,…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ WPbT04Sgp ┆ [Fil      ┆ 2015-10-1 ┆ UC9hHeywc ┆ … ┆ false     ┆ People &  ┆ null      ┆ 0        │
│ zY        ┆ d'Actu    ┆ 5         ┆ PBnLglqnQ ┆   ┆           ┆ Blogs     ┆           ┆          │
│           ┆ #03] Air  ┆ 19:04:24  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆          │
│           ┆ France,   ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ T…        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e3MvTSKhc ┆ [Fil      ┆ 2015-10-0 ┆ UC9hHeywc ┆ … ┆ false     ┆ People &  ┆ police|cr ┆ 0        │
│ LA        ┆ d'Actu    ┆ 9         ┆ PBnLglqnQ ┆   ┆           ┆ Blogs     ┆ oissance| ┆          │
│           ┆ #02]      ┆ 01:22:08  ┆ RaNShQ    ┆   ┆           ┆           ┆ pib|syrie ┆          │
│           ┆ Syrie,    ┆ UTC       ┆           ┆   ┆           ┆           ┆ |ba…      ┆          │
│           ┆ Police…   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PTM5Azmhm ┆ [Fil      ┆ 2015-10-0 ┆ UC9hHeywc ┆ … ┆ false     ┆ People &  ┆ air franc ┆ 0        │
│ Nk        ┆ d'Actu    ┆ 8         ┆ PBnLglqnQ ┆   ┆           ┆ Blogs     ┆ e|chemise ┆          │
│           ┆ spécial]  ┆ 13:27:39  ┆ RaNShQ    ┆   ┆           ┆           ┆ |valls|dr ┆          │
│           ┆ Air       ┆ UTC       ┆           ┆   ┆           ┆           ┆ h|k…      ┆          │
│           ┆ Franc…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Gx75guyRG ┆ [Fil      ┆ 2015-10-0 ┆ UC9hHeywc ┆ … ┆ false     ┆ News &    ┆ ONU|Volks ┆ 0        │
│ JY        ┆ d'Actu    ┆ 1         ┆ PBnLglqnQ ┆   ┆           ┆ Politics  ┆ wagen|shk ┆          │
│           ┆ #01] Volk ┆ 15:03:03  ┆ RaNShQ    ┆   ┆           ┆           ┆ relli|dar ┆          │
│           ┆ swagen,   ┆ UTC       ┆           ┆   ┆           ┆           ┆ apr…      ┆          │
│           ┆ O…        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Lorsque l'on veut créer des chaînes de caractères, il faut les intégrer dans l'objet polars `pl.lit()` :

In [40]:
df = df.with_columns(
    pl.when(pl.col("view_count") > 100000)
    .then(pl.lit("y a eu bcp de vu"))
    .when((pl.col("view_count") < 100000) & (pl.col("view_count") > 50000))
    .then(pl.lit("ouais bof"))
    .otherwise(pl.lit("pas ouf"))
    .alias("a_peu_pres_bis")
)
df.head()

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ video_id  ┆ video_tit ┆ published ┆ channel_i ┆ … ┆ category  ┆ tags      ┆ a_peu_pre ┆ a_peu_pr │
│ ---       ┆ le        ┆ _at       ┆ d         ┆   ┆ ---       ┆ ---       ┆ s         ┆ es_bis   │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ ---       ┆ ---      │
│           ┆ str       ┆ datetime[ ┆ str       ┆   ┆           ┆           ┆ i32       ┆ str      │
│           ┆           ┆ μs, UTC]  ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1_UCKSs88 ┆ ÉTAT DE   ┆ 2025-01-1 ┆ UC9hHeywc ┆ … ┆ News &    ┆ trump|mac ┆ 100000    ┆ y a eu   │
│ fw        ┆ LA        ┆ 9         ┆ PBnLglqnQ ┆   ┆ Politics  ┆ ron|inves ┆           ┆ bcp de   │
│           ┆ FRANCE :  ┆ 16:45:53  ┆ RaNShQ    ┆   ┆           ┆ titure|ba ┆           ┆ vu       │
│           ┆ CE        ┆ UTC       ┆           ┆   ┆           ┆ yro…      ┆           ┆          │
│           ┆ MENSONG…  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Hc9UD6iil ┆ FRANCE :  ┆ 2024-12-2 ┆ UC9hHeywc ┆ … ┆ News &    ┆ macron|ba ┆ 50000     ┆ ouais    │
│ NY        ┆ LA        ┆ 2         ┆ PBnLglqnQ ┆   ┆ Politics  ┆ yrou|1er  ┆           ┆ bof      │
│           ┆ SITUATION ┆ 16:30:04  ┆ RaNShQ    ┆   ┆           ┆ ministre| ┆           ┆          │
│           ┆ POLITIQU… ┆ UTC       ┆           ┆   ┆           ┆ que…      ┆           ┆          │
│ -32lgROAm ┆ QUI VEUT  ┆ 2024-11-2 ┆ UC9hHeywc ┆ … ┆ News &    ┆ agriculte ┆ 50000     ┆ ouais    │
│ DQ        ┆ LA PEAU   ┆ 5         ┆ PBnLglqnQ ┆   ┆ Politics  ┆ ur|en col ┆           ┆ bof      │
│           ┆ DES AGRIC ┆ 16:37:23  ┆ RaNShQ    ┆   ┆           ┆ ère|agric ┆           ┆          │
│           ┆ ULTE…     ┆ UTC       ┆           ┆   ┆           ┆ ult…      ┆           ┆          │
│ BI_fweGoR ┆ TRUMP     ┆ 2024-11-1 ┆ UC9hHeywc ┆ … ┆ News &    ┆ trump|elo ┆ 100000    ┆ y a eu   │
│ JU        ┆ RÉÉLU :   ┆ 2         ┆ PBnLglqnQ ┆   ┆ Politics  ┆ n musk|te ┆           ┆ bcp de   │
│           ┆ QUELLES   ┆ 16:29:44  ┆ RaNShQ    ┆   ┆           ┆ sla|starl ┆           ┆ vu       │
│           ┆ IMPLICAT… ┆ UTC       ┆           ┆   ┆           ┆ igh…      ┆           ┆          │
│ D1pQ6c1T8 ┆ MOLDAVIE, ┆ 2024-10-3 ┆ UC9hHeywc ┆ … ┆ News &    ┆ macron|ba ┆ 100000    ┆ y a eu   │
│ X4        ┆ GÉORGIE,  ┆ 1         ┆ PBnLglqnQ ┆   ┆ Politics  ┆ rnier|éco ┆           ┆ bcp de   │
│           ┆ BRICS :   ┆ 16:37:10  ┆ RaNShQ    ┆   ┆           ┆ nomie|bud ┆           ┆ vu       │
│           ┆ L'E…      ┆ UTC       ┆           ┆   ┆           ┆ get…      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Il est aussi possible de changer le type d'une colonne (à utiliser avec modération), ou d'effectuer plusieurs modifications **en même temps**.

In [41]:
df.with_columns(
    pl.col("like_count").cast(pl.Float64),
    (pl.col("comment_count") ** 2).alias("comment_count_p2")
)

shape: (370, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ video_id  ┆ video_tit ┆ published ┆ channel_i ┆ … ┆ tags      ┆ a_peu_pre ┆ a_peu_pre ┆ comment_ │
│ ---       ┆ le        ┆ _at       ┆ d         ┆   ┆ ---       ┆ s         ┆ s_bis     ┆ count_p2 │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆ datetime[ ┆ str       ┆   ┆           ┆ i32       ┆ str       ┆ i64      │
│           ┆           ┆ μs, UTC]  ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1_UCKSs88 ┆ ÉTAT DE   ┆ 2025-01-1 ┆ UC9hHeywc ┆ … ┆ trump|mac ┆ 100000    ┆ y a eu    ┆ 561001   │
│ fw        ┆ LA        ┆ 9         ┆ PBnLglqnQ ┆   ┆ ron|inves ┆           ┆ bcp de vu ┆          │
│           ┆ FRANCE :  ┆ 16:45:53  ┆ RaNShQ    ┆   ┆ titure|ba ┆           ┆           ┆          │
│           ┆ CE        ┆ UTC       ┆           ┆   ┆ yro…      ┆           ┆           ┆          │
│           ┆ MENSONG…  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Hc9UD6iil ┆ FRANCE :  ┆ 2024-12-2 ┆ UC9hHeywc ┆ … ┆ macron|ba ┆ 50000     ┆ ouais bof ┆ 320356   │
│ NY        ┆ LA        ┆ 2         ┆ PBnLglqnQ ┆   ┆ yrou|1er  ┆           ┆           ┆          │
│           ┆ SITUATION ┆ 16:30:04  ┆ RaNShQ    ┆   ┆ ministre| ┆           ┆           ┆          │
│           ┆ POLITIQU… ┆ UTC       ┆           ┆   ┆ que…      ┆           ┆           ┆          │
│ -32lgROAm ┆ QUI VEUT  ┆ 2024-11-2 ┆ UC9hHeywc ┆ … ┆ agriculte ┆ 50000     ┆ ouais bof ┆ 484416   │
│ DQ        ┆ LA PEAU   ┆ 5         ┆ PBnLglqnQ ┆   ┆ ur|en col ┆           ┆           ┆          │
│           ┆ DES AGRIC ┆ 16:37:23  ┆ RaNShQ    ┆   ┆ ère|agric ┆           ┆           ┆          │
│           ┆ ULTE…     ┆ UTC       ┆           ┆   ┆ ult…      ┆           ┆           ┆          │
│ BI_fweGoR ┆ TRUMP     ┆ 2024-11-1 ┆ UC9hHeywc ┆ … ┆ trump|elo ┆ 100000    ┆ y a eu    ┆ 1760929  │
│ JU        ┆ RÉÉLU :   ┆ 2         ┆ PBnLglqnQ ┆   ┆ n musk|te ┆           ┆ bcp de vu ┆          │
│           ┆ QUELLES   ┆ 16:29:44  ┆ RaNShQ    ┆   ┆ sla|starl ┆           ┆           ┆          │
│           ┆ IMPLICAT… ┆ UTC       ┆           ┆   ┆ igh…      ┆           ┆           ┆          │
│ D1pQ6c1T8 ┆ MOLDAVIE, ┆ 2024-10-3 ┆ UC9hHeywc ┆ … ┆ macron|ba ┆ 100000    ┆ y a eu    ┆ 1454436  │
│ X4        ┆ GÉORGIE,  ┆ 1         ┆ PBnLglqnQ ┆   ┆ rnier|éco ┆           ┆ bcp de vu ┆          │
│           ┆ BRICS :   ┆ 16:37:10  ┆ RaNShQ    ┆   ┆ nomie|bud ┆           ┆           ┆          │
│           ┆ L'E…      ┆ UTC       ┆           ┆   ┆ get…      ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ vxZ6U0Njc ┆ [Fil      ┆ 2015-10-2 ┆ UC9hHeywc ┆ … ┆ bernie    ┆ 0         ┆ pas ouf   ┆ 16       │
│ 6M        ┆ d'Actu    ┆ 4         ┆ PBnLglqnQ ┆   ┆ sanders|h ┆           ┆           ┆          │
│           ┆ #04] Le   ┆ 00:07:39  ┆ RaNShQ    ┆   ┆ iver|sdf| ┆           ┆           ┆          │
│           ┆ froid     ┆ UTC       ┆           ┆   ┆ logem…    ┆           ┆           ┆          │
│           ┆ tue,…     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ WPbT04Sgp ┆ [Fil      ┆ 2015-10-1 ┆ UC9hHeywc ┆ … ┆ null      ┆ 0         ┆ pas ouf   ┆ 81       │
│ zY        ┆ d'Actu    ┆ 5         ┆ PBnLglqnQ ┆   ┆           ┆           ┆           ┆          │
│           ┆ #03] Air  ┆ 19:04:24  ┆ RaNShQ    ┆   ┆           ┆           ┆           ┆          │
│           ┆ France,   ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ T…        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e3MvTSKhc ┆ [Fil      ┆ 2015-10-0 ┆ UC9hHeywc ┆ … ┆ police|cr ┆ 0         ┆ pas ouf   ┆ 49       │
│ LA        ┆ d'Actu    ┆ 9         ┆ PBnLglqnQ ┆   ┆ oissance| ┆           ┆           ┆          │
│           ┆ #02]      ┆ 01:22:08  ┆ RaNShQ    ┆   ┆ pib|syrie ┆           ┆           ┆          │
│           ┆ Syrie,    ┆ UTC       ┆           ┆   ┆ |ba…      ┆           ┆           ┆          │
│           ┆ Police…   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PTM5Azmhm ┆ [Fil      ┆ 2015-10-0 ┆ UC9hHeywc ┆ … ┆ air franc ┆ 0         ┆ pas ouf   ┆ 1764     │
│ Nk        ┆ d'Actu    ┆ 8         ┆ PBnLglqnQ ┆   ┆ e|chemise ┆           ┆           ┆          │
│           ┆ spécial]  ┆ 13:27:39  ┆ RaNShQ    ┆   ┆ |valls|dr ┆           ┆           ┆          │
│           ┆ Air       ┆ UTC       ┆           ┆   ┆ h|k…      ┆           ┆           ┆          │
│           ┆ Franc…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Gx75guyRG ┆ [Fil      ┆ 2015-10-0 ┆ UC9hHeywc ┆ … ┆ ONU|Volks ┆ 0         ┆ pas ouf   ┆ 784      │
│ JY        ┆ d'Actu    ┆ 1         ┆ PBnLglqnQ ┆   ┆ wagen|shk ┆           ┆           ┆          │
│           ┆ #01] Volk ┆ 15:03:03  ┆ RaNShQ    ┆   ┆ relli|dar ┆           ┆           ┆          │
│           ┆ swagen,   ┆ UTC       ┆           ┆   ┆ apr…      ┆           ┆           ┆          │
│           ┆ O…        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## 2.8. Grouper des observations

In [42]:
df.group_by("comment_count").agg(pl.col("video_id"))

shape: (310, 2)
┌───────────────┬─────────────────────────────────┐
│ comment_count ┆ video_id                        │
│ ---           ┆ ---                             │
│ i64           ┆ list[str]                       │
╞═══════════════╪═════════════════════════════════╡
│ 1287          ┆ ["gkbZagN3Mlc"]                 │
│ 0             ┆ ["ywUtWliNjmU", "_0NlGDGCGYw",… │
│ 136           ┆ ["ibG0Dk1JDGk"]                 │
│ 872           ┆ ["9etzp2v_Ivg"]                 │
│ 1266          ┆ ["d1fKMGtMtdQ"]                 │
│ …             ┆ …                               │
│ 1406          ┆ ["Bm-aXRFKeCQ"]                 │
│ 146           ┆ ["oAI6Kx5pZ9k"]                 │
│ 2028          ┆ ["5o0NrNh3lKU"]                 │
│ 1866          ┆ ["yhBjGr5gO8U"]                 │
│ 84            ┆ ["BXzsk_2SuB4"]                 │
└───────────────┴─────────────────────────────────┘

In [43]:
df.group_by("comment_count").agg(pl.col("like_count").mean().alias("like_mean"))

shape: (310, 2)
┌───────────────┬───────────┐
│ comment_count ┆ like_mean │
│ ---           ┆ ---       │
│ i64           ┆ f64       │
╞═══════════════╪═══════════╡
│ 1807          ┆ 19618.0   │
│ 1436          ┆ 15096.0   │
│ 470           ┆ 5674.0    │
│ 1538          ┆ 13265.0   │
│ 717           ┆ 5073.0    │
│ …             ┆ …         │
│ 441           ┆ 4159.0    │
│ 2011          ┆ 13720.0   │
│ 608           ┆ 7329.0    │
│ 674           ┆ 6576.0    │
│ 25            ┆ 369.0     │
└───────────────┴───────────┘

## 2.9. Joindre deux dataframes avec des colonnes en commun

In [44]:
df1 = pl.read_csv("videos.csv")
df2 = pl.read_csv("comments_100.csv")

In [45]:
df2.join(
    df1.select(["video_id", "video_title"]),
    on="video_id"
).head(5)

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ video_id   ┆ comment_id ┆ channel_id ┆ text      ┆ like_coun ┆ published ┆ reply_cou ┆ video_tit │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ t         ┆ _at       ┆ nt        ┆ le        │
│ str        ┆ str        ┆ str        ┆ str       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆           ┆ i64       ┆ str       ┆ i64       ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1_UCKSs88f ┆ UgwiW_SF2V ┆ UC9hHeywcP ┆ VIDÉO     ┆ 159       ┆ 2025-01-1 ┆ 10        ┆ ÉTAT DE   │
│ w          ┆ CchkX8gwd4 ┆ BnLglqnQRa ┆ LIÉE :    ┆           ┆ 9T16:50:0 ┆           ┆ LA        │
│            ┆ AaABAg     ┆ NShQ       ┆           ┆           ┆ 0Z        ┆           ┆ FRANCE :  │
│            ┆            ┆            ┆ NON,      ┆           ┆           ┆           ┆ CE        │
│            ┆            ┆            ┆ MACRON NE ┆           ┆           ┆           ┆ MENSONG…  │
│            ┆            ┆            ┆ «…        ┆           ┆           ┆           ┆           │
│ 1_UCKSs88f ┆ UgybOcLb7B ┆ UCW8cAAFV5 ┆ C'est     ┆ 0         ┆ 2025-02-0 ┆ 0         ┆ ÉTAT DE   │
│ w          ┆ R5PCSVG994 ┆ 0hfiktZp2B ┆ quoi le   ┆           ┆ 3T14:31:2 ┆           ┆ LA        │
│            ┆ AaABAg     ┆ ZZvA       ┆ nom de la ┆           ┆ 3Z        ┆           ┆ FRANCE :  │
│            ┆            ┆            ┆ musiqu…   ┆           ┆           ┆           ┆ CE        │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ MENSONG…  │
│ 1_UCKSs88f ┆ Ugw1kBEnQ3 ┆ UCI--K5E29 ┆ Ok mais   ┆ 0         ┆ 2025-02-0 ┆ 0         ┆ ÉTAT DE   │
│ w          ┆ J1mNRCVoh4 ┆ -eK-2s_Qbp ┆ maintenan ┆           ┆ 3T14:08:3 ┆           ┆ LA        │
│            ┆ AaABAg     ┆ IgzA       ┆ t qu’on a ┆           ┆ 2Z        ┆           ┆ FRANCE :  │
│            ┆            ┆            ┆ tou…      ┆           ┆           ┆           ┆ CE        │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ MENSONG…  │
│ 1_UCKSs88f ┆ UgykgAiDn2 ┆ UCOkVLaKsD ┆ Ces gens  ┆ 0         ┆ 2025-02-0 ┆ 0         ┆ ÉTAT DE   │
│ w          ┆ VBvDjHDR54 ┆ 4zgYcHgwZ7 ┆ sont comp ┆           ┆ 2T20:02:3 ┆           ┆ LA        │
│            ┆ AaABAg     ┆ Pkzw       ┆ lètement  ┆           ┆ 8Z        ┆           ┆ FRANCE :  │
│            ┆            ┆            ┆ fou…      ┆           ┆           ┆           ┆ CE        │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ MENSONG…  │
│ 1_UCKSs88f ┆ Ugx1gH5fU1 ┆ UCaVyeJ4gC ┆ Mi physio ┆ 0         ┆ 2025-02-0 ┆ 0         ┆ ÉTAT DE   │
│ w          ┆ XilxY4gLt4 ┆ b5ZyiMffkf ┆ crate, mi ┆           ┆ 2T13:04:2 ┆           ┆ LA        │
│            ┆ AaABAg     ┆ pk1g       ┆ communist ┆           ┆ 0Z        ┆           ┆ FRANCE :  │
│            ┆            ┆            ┆ e …       ┆           ┆           ┆           ┆ CE        │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ MENSONG…  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘